### ISSUE TITLE
Properties import/export

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#10]
Seems like the .wsp files generated by WSH panel mod and JScript Panel aren't compatible with this. I guess it just needs mentioning in the docs/wiki or maybe take the opportunity to change the file extension used by SMP??

**Comment by TheQwertiest** [comment]
Thanks for the report!
This incompatibility was not intentional, so I'll check if it can be fixed.

**Comment by marc2k3** [comment]
Actually, there is far more serious issue - you can't edit text or boolean fields in place. Consider...

```js
var number = window.GetProperty("number", 1);
var bool = window.GetProperty("bool", true);
var text = window.GetProperty("text", "Hello");

console.log(number, bool, text);
```

Now open the Properties dialog and manually edit the values and click Apply. Only changing the number works. Switching the value of "bool" to false changes to number and there is no longer a drop down box. And changing the text string simply does not stick.

I'd not noticed before because I provide dialogs/menus for all my settings but I know many scripts depend on this dialog to changing settings directly.

**Comment by TheQwertiest** [comment]
Weird, I've tested this before and it worked, guess I broke it later...
PS: I will 'submodule' your scripts repository to replace the current 'complete' samples, if it's alright with you.

**Comment by marc2k3** [comment]
Yup, that's fine. I'll update the include paths after you've done it.

**Comment by TheQwertiest** [comment]
Moved property bug to a separate issue #12

**Comment by TheQwertiest** [comment]
Yup, I see now, property export format change was inevitable, I'll see though, if it's possible to make import backwards compatible with WSH/JScript format.

**Comment by TheQwertiest** [comment]
Added ability to import .wsp configs + a new .smp extension for configs in new format.

**Comment by marc2k3** [comment]
Thanks again!!
