### ISSUE TITLE
Pseudo transparent mode is broken in nightly build

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#101]
Your panel has a solid black background when enabled. I guess it's the changes in the C* commit??

https://github.com/TheQwertiest/foo_spider_monkey_panel/commit/c0a58130efe2f17f5f04016441e942b6ac9673c3

JSP/SMP next to each other...

![image](https://user-images.githubusercontent.com/34617027/71068958-afa2f400-216f-11ea-9752-b6e6d093c468.png)

**Comment by TheQwertiest** [comment]
Nice catch, thanks!
