### ISSUE TITLE
GetProperty doesn't work properly when name contains whistespace at beggining

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#106]
Hi,
It look like a property isn't saved or grabbed correctly when it's named with a whitespace at the beggining. You can try with the following code:

console.log(window.GetProperty(" space", "space1"));
window.SetProperty(" space", "space2");
console.log(window.GetProperty(" space"));

In the console you will get
space1
space2
No matter how many time you refresh the console

**Comment by TheQwertiest** [comment]
Thanks for the report =)

**Comment by Ottodix** [comment]
No, thanks for the fix! : )
