### ISSUE TITLE
"on_focus" or "on_focus_changed"

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#11]
In JScript panel/WSH panel mod, it's simply `on_focus` but when I discovered it no longer works, I searched the source and found you've updated it to `on_focus_changed` - which does work as expected, But the docs still state `on_focus`...

https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/50bf4b0e3e63d142079740e4a21543dcec530ab8/component/docs/Callbacks.js#L35

**Comment by TheQwertiest** [comment]
Hm, did I? Gonna check it out
