### ISSUE TITLE
setup.py has issues unpacking mozjs

### ISSUE THREAD

**Issue by kbuffington** [TheQwertiest/foo_spider_monkey_panel#110]
Running setup.py using Python 3.8 gives the following error:

```
>> MozJs unpacking: starting
Traceback (most recent call last):
  File "setup.py", line 25, in wrapper
    f(*args, **kwds)
  File "D:\Source\foo_spider_monkey_panel\scripts\unpack_mozjs.py", line 24, in unpack
    assert(zipfile.is_zipfile(zip_arc))
AssertionError
<< MozJs unpacking: failure
Setup failed!
```

**Comment by TheQwertiest** [comment]
Hm... That's weird this error means, that the downloaded mozjs file is not a zip archive.
Do you have `git LFS` installed? Since maybe the `mozjs` file was not downloaded at all.

**Comment by TheQwertiest** [comment]
The full building instructions can be found here: https://theqwertiest.github.io/foo_spider_monkey_panel/docs/for_developers/building_component/

**Comment by kbuffington** [comment]
Might have been LFS. I didn't have that installed when I originally did `git submodule update` and the .zip file was just a 1k git pointer file. Anyway, I deleted the folder, and re-ran `update` and now it looks good and `setup.py` runs correctly.
