### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by 2ji3150** [TheQwertiest/foo_spider_monkey_panel#111]
Sorry I don't know is this about the Plugin  or this can be achieve by the script.

Just hope that webp can be decode on the marc2003's scripts.

Is that possible? 

BTW,I saw that the pulgin "columns_ui" shift to use the The Windows Imaging Component so it can decode WEBP and HEIF now.

**Comment by TheQwertiest** [comment]
I think it might be possible on semi-new Windows 10, but I haven't looked into that. I won't work on this feature in the near future though, but I'll leave it open as a reminder.

**Comment by 2ji3150** [comment]
Yes, It is support on the Windows 10 Version 1809 (October 2018 Update)
But for those earlier version windows , the WIC-Support Webp component can be download from the Webp official webpages. 
https://storage.googleapis.com/downloads.webmproject.org/releases/webp/WebpCodecSetup.exe

**Comment by 2ji3150** [comment]
Foobar2000 1.6 Suppport WEBP now. Seem there will be new SDK also. Not really know would this benefit SMP.

**Comment by redactedscribe** [comment]
Would also love to see WebP support in SMP ❤

**Comment by marc2k3** [comment]
The built in album art functions should already support it without any code changes. But it only works on external webp files, not embedded ones.

This means the following scripts should display them
complete\album art
jsplaylist-mod
js-smooth browser
js-smooth playlist

And of course any other scripts that make use of utils.GetAlbumArtV2, GetAlbumArtAsync etc.

**Comment by redactedscribe** [comment]
Just upgraded to foobar2000 v1.6 ("Added support for WebP album covers (Default UI, Properties dialog)") and wanted to try those scripts mentioned above.

I made sure `front.*` was defined in fb2k's prefs for front cover album art and then imported `complete\album art.js` into SMP. Switching via right-click between the Back and Front views shows that the placeholder image is being displayed for Back but a blank screen is shown for Front - it finds the file, but can't display it (for whatever reason). I also have a `front.webp` in the music directory in question, and switched off and back onto the album to "refresh" fb2k, so those shouldn't be the problem. Can't get a WebP to load. Seemed no better with `jsplaylist main script.js`.

Seems it doesn't just work out of the box then as marc thought it may.

SMP v1.3.1

**Comment by TheQwertiest** [comment]
I haven't tested WebP support yet, but I'll look into it.

**Comment by 2ji3150** [comment]
upgrade to foobar2000 1.6 with SMP v1.3.1. Looks not all of the script works property with cover.webp. 

For example, In **JS Smooth Browser** the artworks are displayed. But the background image (which is the palying artwork ) is not displayed.

Guess it may be related to   `utils.GetAlbumArtV2`

**Comment by TheQwertiest** [comment]
@2ji3150 , dunno, I'll have to look into it. Not sure that I'll have much free time this month though...

**Comment by marc2k3** [comment]
I've implemented webp support in JScript Panel but I'd never use it. Decode performance really sucks taking tens or even hundreds of milliseconds to decode an image that would take less than 1ms in jpg format.

**Comment by 2ji3150** [comment]
> I've implemented webp support in JScript Panel but I'd never use it. Decode performance really sucks taking tens or even hundreds of milliseconds to decode an image that would take less than 1ms in jpg format.

I think the Webp API has a multi-threaded decoding function. 
Isn't it implemented in Foobar2000? 
However, I've been using WEBP a lot and  a long time. 
Never notice or feel that decoding is slower than JPG.

**Comment by marc2k3** [comment]
I should have clarified...obviously you'd never notice the difference when having an artwork view panel that updates itself every time the track changes. I'm thinking more about library viewers/other scripts that load dozens/hundreds of images at once.

**Comment by 2ji3150** [comment]
# Status update

## Environment
+ Spider Monkey Panel 1.4.1 
+ Foobar2000 1.6.4

## Test Script

js-smooth\script 
complete\album art
basic\GetAlbumArtV2

None of theese script can recongnize webp image.

And also test the lastes Jscript Panel 2.5.3 with theese scripts, works well with webp images.

**Comment by TheQwertiest** [comment]
Well, it's as expected, since WebP support is yet to be implemented =)
