### ISSUE TITLE
Option to disable "Follow active playlist" in JSPlaylist-mod

### ISSUE THREAD

**Issue by raphaelquast** [TheQwertiest/foo_spider_monkey_panel#114]
Hi,
thanks a lot for your very useful plugin!
I've started incorporating it in my [TripleQ theme](https://github.com/raphaelquast/foobar2000_TripleQ) and so far I'm more than satisfied! 😃 

I don't know if this is the right place to ask but since the jsplaylist-mod script is included in the component I thought I'll give it a try...

My problem is that the included `jsplaylist-mod` script always keeps it's focus on the active playlist. This however is quite annoying if you would like to display more than 1 playlist-views at the same time...

Is there any (reasonably simple) workaround to get rid of this behaviour (or would it be possible to implement a "Follow active playlist > Yes/No" button like in [ESplaylist](https://hydrogenaud.io/index.php?topic=79030.0)) ?

**Comment by TheQwertiest** [comment]
Sorry, `jsplaylist-mod` was ported and maintained by marc2003, so I'm not familiar enough with it's code to implement such features.

**Comment by raphaelquast** [comment]
OK, thanks for the response!
