### ISSUE TITLE
incremental search bug in sample script (jssb.js)

### ISSUE THREAD

**Issue by seongbin** [TheQwertiest/foo_spider_monkey_panel#115]
When I set the ppt.sourceMode as 1 which is from playlist (default is from library), the incremental search (searching relevant album artist or artist by keydown) cannnot process as expected. I tried to find marc2k3's repo to post it first, but it looks like he removed jscript panel repo on his account.

**Comment by TheQwertiest** [comment]
Thanks for reporting the issue. Regretfully, I'm not familiar enough with the script (it was maintained mostly by marc2k3).
Not saying that I won't fix it, but rather that it won't be fixed any time soon.

**Comment by seongbin** [comment]
Thanks for reply and appreciate it.

**Comment by marc2k3** [comment]
I have no idea how to fix this so I just return early from the **on_char** function to prevent characters appearing on screen giving the false impression that something should be happening.

https://github.com/marc2k3/foo_jscript_panel/blob/51c44927eca2866aa2f2d5fa31ae5aea5aa8598f/component/samples/js-smooth/js/jssb.js#L3540

**Comment by TheQwertiest** [comment]
I've applied marc's workaround. Regretfully, I think that's the most that I can do regarding this issue.
