### ISSUE TITLE
The unicode code and symbol seems wrong,which variable in 'helpers.js' named 'chars'.

### ISSUE THREAD

**Issue by zhsh00** [TheQwertiest/foo_spider_monkey_panel#117]
when i study the example in 'samples/complete/track info + seekbar + buttons.js',i found these icons are empty.

then i baidu,the unicode character code and found this link：they show the match between code and symbol.

the code in helpers.js：
`
let chars = {
	up : '\uF077',  
	down : '\uF078',  
	close : '\uF00D',  
	rating_on : '\uF005',  
	rating_off : '\uF006',  
	heart_on : '\uF004',  
	heart_off : '\uF08A',  
	prev : '\uF049',  
	next : '\uF050',  
	play : '\uF04B',  
	pause : '\uF04C',  
	stop : '\uF04D',  
	preferences : '\uF013',  
	search : '\uF002',  
	console : '\uF120',  
	info : '\uF05A',  
	audioscrobbler : '\uF202',  
	minus : '\uF068',  
	music : '\uF001',  
	menu : '\uF0C9'  
};
`

[杂项工业符号 Unicode字符表](http://52unicode.com/miscellaneous-technical-zifu)
![截图](http://m.qpic.cn/psc?/V10tFB991ezNJN/bqQfVz5yrrGYSXMvKr.cqbmFIegKbsKS4kg19LaLlzYD5CDcpBE2CSfBpqRHWuzjVH29334fc7m*5eR1oS1Fln.Z77jrKSsY64YBeolDI.Q!/mnull&bo=0QNiAQAAAAADB5M!&rf=photolist&t=5)

**Comment by marc2k3** [comment]
You need to install FontAwesome.

https://github.com/FortAwesome/Font-Awesome/blob/fa-4/fonts/fontawesome-webfont.ttf?raw=true

**Comment by TheQwertiest** [comment]
What marc said =)
