### ISSUE TITLE
return value from img.SaveAs() on completion

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#118]
Hi TheQwertiest,

Currently calling this function will save the image asynchronously, so the script continue its execution.
Would it be possible to know when the image have been saved succesfully in order to execute a code right after completion?

**Comment by Ottodix** [comment]
I just managed to find a turnaround which is good enough:
```
img.SaveAs(filepath, "image/jpeg");
var WshShell = new ActiveXObject("WScript.Shell");
var FileSyst = new oFileSystObject();
var check_fileExist = setInterval(function(filepath) {		
	if(FileSyst.FileExists(filepath)) {
		window.ClearInterval(check_fileExist);
		//do someting		
	}
		
},30,filepath);
```

So I close this ticket

**Comment by Ottodix** [comment]
Actually this turnaround isn't so perfect... because the FileExists method return true if the image is in the process of beeing saved but not completely finished. I could add a random delay, but I would prefer something more robust and clean
Do you have an idea there ?

**Comment by marc2k3** [comment]
This method should block until it's done plus it already returns a boolean to indicate success or failure.

**Comment by Ottodix** [comment]
I'm trying to open the image using an external application directly after calling SaveAs, and I've got errors. But it's very possible that the errors come from something else then. (from an issue with this external application)

**Comment by Ottodix** [comment]
Yep, I've been able to reproduce the issue out of foobar, ok thanks marc2k3, closed (again)
