### ISSUE TITLE
Is it possible to add a menu item to open *.html help file(s)?

### ISSUE THREAD

**Issue by elia-is-me** [TheQwertiest/foo_spider_monkey_panel#122]
![Img_2020-09-14_20-00-53](https://user-images.githubusercontent.com/5344103/93083672-8646d280-f6c5-11ea-8082-4f1a2d61ecfe.png)
Like in this image?

**Comment by TheQwertiest** [comment]
There *is* one in Panel Configuration dialog though: 
![image](https://user-images.githubusercontent.com/4470278/93132789-e8600180-f6de-11ea-9e2c-d4014c570ef9.png)

Any reason why you want to access it via main menu specifically? =)

**Comment by elia-is-me** [comment]
sorry i did not notice it;
maybe because i seldom use panel's default editor, in fact when writing scripts i prefer use my own code editor and through 'Reload' menu to update panel. So it's a little difficult for me to get access to the menu item;
Just in my view that a menu item under the global 'Help' menu or right click popup menu would be proper and easier to get to.

**Comment by TheQwertiest** [comment]
Ok, will be added.
PS: `panel configure v2` rewrite includes ability to specify your default text editor.

**Comment by TheQwertiest** [comment]
I've (freaking finally) implemented configure v2, so now (among many other things) you can specify any other text editor you want to edit scripts =)

**Comment by TheQwertiest** [comment]
Added in nightly build
