### ISSUE TITLE
HtmlDialogWithCheckBox.js sample not working

### ISSUE THREAD

**Issue by Isabelxxx** [TheQwertiest/foo_spider_monkey_panel#124]
Hi,
I have been trying to work with the HTML sample given but the <script> part on the HTML file is never loaded, not sure what's wrong. I tried first to check the sample "as is" without luck (ok button does nothing), then I simply deleted every line of code an just put a console log on the script part of the HTML file, and nothing... so something must be wrong somewhere.

Btw I'm on win 7. Last version of the plugin.

**Comment by TheQwertiest** [comment]
Do you have Internet Explorer 9 installed?

**Comment by Isabelxxx** [comment]
Nope, I use other browsers and have explorer totally removed.

**Comment by TheQwertiest** [comment]
As per docs (https://theqwertiest.github.io/foo_spider_monkey_panel/assets/generated_files/docs/html/utils.html#.ShowHtmlDialog): `Utilizes the latest non-Edge IE that you have on your system.`

So, if there is no IE installed, than it just can't work.

**Comment by Isabelxxx** [comment]
My fault. I totally missed that point!

Will try installing it.
