### ISSUE TITLE
fb.DoDragDrop custom_image issues

### ISSUE THREAD

**Issue by elia-is-me** [TheQwertiest/foo_spider_monkey_panel#125]
I was trying to set a custom image when use fb.DoDragDrop, however the image position was stranger:
https://imgur.com/0rTaA08

and also, fb.DoDragDrop would not do anything if `handle_list` is NULL or  an empty metadb_list, is it designed to be?

**Comment by TheQwertiest** [comment]
> I was trying to set a custom image when use fb.DoDragDrop, however the image position was stranger:

Can you provide a sample script, please?

> and also, fb.DoDragDrop would not do anything if handle_list is NULL or an empty metadb_list, is it designed to be?

Yep. Since you can't drag -n-drop nothingness :D

**Comment by TheQwertiest** [comment]
Ok, I've reproduced the issue, but have no idea how to fix it properly: drag-n-drop API is an undocumented arcane mess on Windows >_<
We'll see if I think of something.

**Comment by TheQwertiest** [comment]
Not sure if what I did is a proper fix that won't bite me in the butt in the future, but it works (for now) =)
