### ISSUE TITLE
Crash when used as DUI element

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#129]
Seems fine in Columns UI.

Also, the Editor Properties window is borked. You can't edit any values.

**Comment by TheQwertiest** [comment]
Thanks for testing and reporting! I'll look into it.

**Comment by TheQwertiest** [comment]
Should be fixed in the latest nightly (once it's built)

**Comment by TheQwertiest** [comment]
Editor Properties was actually bugged for a loooooong time >_<

**Comment by TheQwertiest** [comment]
New nightly has been built.
