### ISSUE TITLE
Handling invalid album art ids

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#13]
Only 0-4 are valid and if you supply JScript Panel/WSH panel with an invalid value, it would default to 0 which is the front cover. Your update defaults to 4 (artist image) which is what caused the issue I mentioned the other day with Br3tt's JS-Smooth scripts. 

Of course this entirely down to awful script writing - he was supplying insane values but JSP was hiding the problem by displaying front covers which I guess most people want anyway. I've now fixed this in the script and it works as expected with your component but since you've been on a mission to throw errors when supplied with out of range values, perhaps it would be an idea to "fix" this component side too.

**Comment by TheQwertiest** [comment]
It was actually just a typo. It will return 0 now as it did before (see https://github.com/TheQwertiest/foo_spider_monkey_panel/commit/9012204713f04a4e660c86be9cec9c0d9bca0555).

I will close this issue once I add more rigid error checking (this won't happen till next release though).

**Comment by marc2k3** [comment]
That doesn't work!! It returns 0 for valid selections between 1 and 4 also.

Load `samples\complete\album art.txt` and you can see for yourself. Perhaps...

```cpp
if ( art_id > _countof( guids ) - 1 )
{
    art_id = 0;
}
return *guids[ art_id ];

**Comment by TheQwertiest** [comment]
Ugh, sorry for that, got distracted a bit -_-

**Comment by marc2k3** [comment]
I think I'll forgive you. :laughing:  You've clearly put an extreme amount of time and effort in to this. Thanks for everything so far.

**Comment by TheQwertiest** [comment]
The bug with invalid art_id is hopefully fixed with 854dae5d599a4380110b1678d54bd654cb95cba2

**Comment by marc2k3** [comment]
Unfortunately, I'm too lazy to systematically test every method and callback - I'm just reporting things as I find them. I'm sure releasing it to the great unwashed will find a few more errors!

**Comment by marc2k3** [comment]
Can confirm the fix. I've also updated JSP because it was using `int` for `art_id` which makes no sense.
