### ISSUE TITLE
Apply button fail

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#130]
From the editor dialog, I expect to be able to hit the Apply button repeatedly if I want to test something...

But on the first click, it doesn't even reset the script. And after that first click it disables itself and won't become active until the text changes. That behaviour is so wrong!

**Comment by TheQwertiest** [comment]
> I expect to be able to hit the Apply button repeatedly if I want to test something...

I'm genuinely curious, what things are you testing that require the reload of the script without actually changing the script?

> But on the first click, it doesn't even reset the script.

Do you mean that after changing the script and clicking on Apply, the panel is not reloaded?

**Comment by marc2k3** [comment]
Currently, the button does nothing. Removing it would make more sense and I'll accept that.

**Comment by TheQwertiest** [comment]
That's strange, how do you open the editor dialog? (coz there's different code for each scenario)
- Configure window: 
  - Edit button in source tab
  - Edit button in package tab
- `window.EditScript()`
- `window.Configure()` (with in-memory script)

**Comment by TheQwertiest** [comment]
Actually, you are right - apply button does not work anymore, I'll take a look it if can be fixed.

**Comment by TheQwertiest** [comment]
It should work now =) (if there were any changes in the script)
