### ISSUE TITLE
utils.WriteTextFile borked in nightly build

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#131]
It writes the file as expected but always throws an error. This is with and without write_bom specified.

Also, when write_bom is false, that's ignored and a BOM is written anyway.

**Comment by TheQwertiest** [comment]
This is weird :D
Thanks for reporting!

**Comment by marc2k3** [comment]
I just noticed you've changed this from returning a bool to void without warning. Intentional?

**Comment by TheQwertiest** [comment]
It was intentional, but it was a bad decision (I was feeling really lazy on that day), since it's a breaking change that doesn't improve much. I.e. I will revert it.
