### ISSUE TITLE
More nightly bugz

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#132]
-Your updated utils get file size code will crash if you supply an invalid path.

-Picking a sample from the combo box results in an error

```
Error: Spider Monkey Panel v1.3.2-beta+01dd8c13 ({358BE023-493E-49E3-AC72-995AC89466D4})
Path does not point to a valid file: Z:\foobar2000 - Copy - Copy\profile\user-components\foo_spider_monkey_panel\samples\..\complete\playback buttons.js
```

Note the `\..\` in the full path.

-Just saw your post on HA about the html parsing bug affect WilB's bio - it also affects thumbs and allmusic from the samples.

**Comment by TheQwertiest** [comment]
> -Picking a sample from the combo box results in an error
Yup, I've noticed that as well, already fixed =)

> -Your updated utils get file size code will crash if you supply an invalid path.
Thanks, didn't have time to test them yesterday >_<

> -Just saw your post on HA about the html parsing bug affect WilB's bio - it also affects thumbs and allmusic from the samples.
That's really weird, AFAIK your samples *did* work in SMP. This ActiveX API is such a major PITA...

**Comment by TheQwertiest** [comment]
> That's really weird, AFAIK your samples did work in SMP. This ActiveX API is such a major PITA

And they *do* work on the release version... Ugh...

**Comment by TheQwertiest** [comment]
Everything should be fixed now (once nightly is built).
Thanks again for testing and reporting!
