### ISSUE TITLE
utils.ShowHtmlDialog does not respect `x-ua-compatible`

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#133]
1)  Does code need to be ie8 compatible?  Doc suggests not, but I find any features introduced after ie8 don't work, even if I use in head : content="IE=11"

The attached is using that header & has an alert test  that checks for support of document.addEventListener (added in ie9)
Am I missing something?

2) Radio buttons: dot doesn't always center. Issue also applies to checkbox & may be related to making window resizable when positioned using a relative method like % of width, for example.

Attached is a slightly modified version of your sample 'PopWithCheckbox' (html and js) that illustrates the issue.
[HtmlDialogWithCheckBox2.zip](https://github.com/TheQwertiest/foo_spider_monkey_panel/files/5944034/HtmlDialogWithCheckBox2.zip)

Check the box and alter width of window. Tick & box don't move together. Doesn't matter for a checkbox, but if it's a radio button then it doesn't look great if its off center.

I've tried removing all the styling but haven't been able to remove the issue.

**Comment by TheQwertiest** [comment]
Thanks for reporting!
IE mode was not applied properly when `ShowHtmlDialog` was used with inlined code (worked properly with files though).
It should be noted, that some styling is broken now in the basic sample and has to be rewritten.
