### ISSUE TITLE
Queue'd Timer Callbacks still execute even after timer is cleared

### ISSUE THREAD

**Issue by kbuffington** [TheQwertiest/foo_spider_monkey_panel#135]
I found some weird behavior that is an issue with FSM, but maybe on the actual SM side of the things? I encountered an issue where a queued setInterval callback (i.e. the interval had fired, but code had not been executed) had it's spawning timer cleared, and then afterwards the callback was still executed. 

What's supposed to happen is that before the callback executes the timerId is checked to see if it's still valid, and if not it's discarded. See [this SO answer](https://stackoverflow.com/questions/47263656/will-clearinterval-stop-queued-interval-execution#47263776). Here's the code snippet:

```
var counter = 0;
var timer = setInterval(function() {
  ++counter;
  console.log("timer fired:", counter);
  if (counter == 1) {
    setTimeout(busyWaitAndClear, 0);
  }
}, 500); // Every 500ms
function busyWaitAndClear() { // Obviously never really do this
  var done = Date.now() + 1000;
  while (done > Date.now()) {
    // wait
  }
  clearInterval(timer);
  console.log("timer cleared");
}
```
You can run that code snippet in any browser and the interval will only execute once. However if you paste that into a FSM panel, the interval will execute 3 times (the initial time and then two more queued callbacks while the busyWait function is spinning for a second). This completely threw me for a loop and I spent a couple hours debugging before I realized the queue'd callbacks were still executing after the clear. Not sure if this is fixable, but my workaround is super ugly so I figured I should let you know :)

![image](https://user-images.githubusercontent.com/2282004/110610643-0c634380-8154-11eb-94c7-afb8765e6479.png)

**Comment by TheQwertiest** [comment]
Thanks, I'll take a look.

**Comment by TheQwertiest** [comment]
Fixed

**Comment by TheQwertiest** [comment]
@kbuffington , I think I'll have to revert the fix to this issue, because I don't think I can fix all the problems that this fix brings.
I'm working on the total rewrite of the event handling system which should fix this issue, but it'll take quite a bit of time and it will probably will bring more bugs =) (being a huge rewrite and all)

**Comment by kbuffington** [comment]
That's fine. I'll revert my revert of my fixes then :)
