### ISSUE TITLE
Constant crashing when right-clicking on album art

### ISSUE THREAD

**Issue by antianastasio** [TheQwertiest/foo_spider_monkey_panel#149]
Hi, I've been having an issue for several days where if I right click on the album art within an artist tab, the panel will immediately crash and produce this error message:

Error: Spider Monkey Panel v1.3.1 (GraphicBrowser v1.2.3b18 by Ottodix)
AppendMenuItem failed:
WinAPI error:
  AppendMenu failed with error (0x0):
    Function failed, but returned a `SUCCESS` error code, which is usually caused by a bugged WinAPI. One such case is when process runs out of GDI handles and can't create a new GDI object.

File: JStheme_common.js
Line: 1880, Column: 58

Stack trace:
  createGenrePopupMenu@JStheme_common.js:1880:58
  on_mouse_rbtn_down@WSHgraphicbrowser_trackinfos.js:6501:25

I've tried fresh reinstalling foobar and my components several times to no avail. Upon fresh install I'm able to right click on the album art as the media library populates but as soon as it's finished scanning and all my artists are imported that's when the crashing starts happening. I appreciate any help you might be able to give me and thank you for your time!

**Comment by TheQwertiest** [comment]
1.3.1 is an old version. Try using 1.5.2 instead and see if the problem still persists.
