### ISSUE TITLE
Properties sort differently to JSP

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#16]
window.GetProperty(" Test", "Position in JSP: 1 [NOTE: NAME HAS A LEADING SPACE THAT'S REMOVED BY SMP]");

window.GetProperty("-Test", "Position in JSP: 2");

window.GetProperty(".Test","Position in JSP: 3");

window.GetProperty("_Test", "Position in JSP: 4");

window.GetProperty("Custom", "Position in JSP: 5");

As a test, the above properties sort in a different order in SMP vs JSP. I've often used a leading space to ensure certain properties sort first, and that isn't currently working. I expect the sort difference effects quite a few scripts, e.g. in "JS Smooth Playlist" the properties that start with _ no longer sort first. Can the sorting be corrected? Else I'll have to change property names which would break importing JSP properties during upgrade.

**Comment by TheQwertiest** [comment]
Leading space was removed intentionally, mostly for consistent behaviour: JSP was already removing trailing spaces.

About sorting of `_` and other symbols: I'll see what I can do, shouldn't be too difficult =)

PS: During SMP testing I've ported your `Library Tree` and `YouTube Manager` scripts ([Library](https://github.com/TheQwertiest/CaTRoX_QWR/blob/smp_update/theme/Scripts/Panel_Library.js), [YT Mgr](https://github.com/TheQwertiest/CaTRoX_QWR/blob/smp_update/theme/Scripts/Panel_YT.js)), so you can use those to fix the simple incompatibility problems that I could find.

**Comment by TheQwertiest** [comment]
`_` should be now treated the same as in JSP.

**Comment by TheQwertiest** [comment]
Oh, forgot to fix trailing spaces in props JSP import.
