### ISSUE TITLE
fb.RunMainMenuCommand("File Operations/Move to/Anything") doesn't work

### ISSUE THREAD

**Issue by FunctionDJ** [TheQwertiest/foo_spider_monkey_panel#162]
I got a few "Move to" configurations set up, but i can't call them using `fb.RunMainMenuCommand`. Other calls, like `"File/Preferences"` work though.
I'd like to run this from code so that i can run some related code afterwards.

**Comment by marc2k3** [comment]
File operations are accessed via the CONTEXT menu, not the MAIN menu.

**Comment by FunctionDJ** [comment]
@marc2k3 that was my issue! thanks a lot! the context/main concept still catches me every now and then xD

**Comment by marc2k3** [comment]
No. Ultimately the component/script is letting you execute C++ methods in the SDK via javascript. There is no magic dialog manipulation.
