### ISSUE TITLE
ActiveX

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#17]
Because this is no longer based on Window Script Host, people might not realise they still need to utilise it for file/folder operations, running external apps, internet access etc. I think it should be mentioned in your readme/docs somewhere.

Also, on the samples readme, you can nuke the IE8 requirement as that was only required for native JSON.parse/stringify.... and it's bundled with Windows 7 which is a minimum requirement anyway. 

The mention of the IE9 requirement for some scripts needs to stay but it isn't script related as such - it's more the secure channel stuff required for connections over https.

**Comment by TheQwertiest** [comment]
> state that you don't care and it's up to others to try it out

Sounds good to me :D

Anyways, I think I've fixed everything you reported in this issue, thus I'm closing it.
