### ISSUE TITLE
Tooltips being cut off with certain fonts

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#171]
Hopefully you can see the issue (window scale & layout is at 125% if that's relevant): 

```
const tooltip = window.Tooltip;

function on_mouse_lbtn_down() {
    tooltip.SetFont('Segoe UI', 24, 1);
    tooltip.Text = 'Load from library'; // displays as 'Load from'
    tooltip.Activate();
}

function on_mouse_mbtn_down() {
    tooltip.SetFont('Segoe UI', 24, 0);
    tooltip.Text = 'Load from library'; // displays correctly
    tooltip.Activate();
}
```

**Comment by TheQwertiest** [comment]
Tooltip width is not adjusted automatically, so you have to do it manually with [Tooltip.SetMaxWidth()](https://theqwertiest.github.io/foo_spider_monkey_panel/assets/generated_files/docs/html/FbTooltip.html#SetMaxWidth)?

**Comment by TheQwertiest** [comment]
ps: plz, reopen if that did not resolve your problem =)
