### ISSUE TITLE
Erratic behavior on name empty

### ISSUE THREAD

**Issue by regorxxx** [TheQwertiest/foo_spider_monkey_panel#176]
- Removing the panel name and clicking on Save adds a UUID for the panel.

- Removing the panel name and clicking on apply or ok without pressing save leaves the panel name empty. (also consider #169 with blank names)

![blank](https://user-images.githubusercontent.com/83307074/176470464-2ea4fec6-5f42-47f5-b528-20191cd73f84.gif)

**Comment by TheQwertiest** [comment]
Thanks! Fixed in dev build

**Comment by regorxxx** [comment]
Btw dev build link throws this error since weeks:

> {"message":"Artifact not found or access denied."}

**Comment by regorxxx** [comment]
Tested and fixed.
