### ISSUE TITLE
Implement callback registration to allow for multiple message handlers

### ISSUE THREAD

**Issue by regorxxx** [TheQwertiest/foo_spider_monkey_panel#177]
https://github.com/TheQwertiest/foo_spider_monkey_panel/projects/1#card-14354341

Just in case you don't want to implement it natively, here it is:
https://github.com/regorxxx/Callbacks-Framework-SMP

**Comment by TheQwertiest** [comment]
Thanks, but `EventTarget` is not the end goal, but rather a means to the end: https://github.com/users/TheQwertiest/projects/1/views/1?filterQuery=feature%3Av2
