### ISSUE TITLE
Is It Possible to Adjust the Scroll Wheels Movement Increment For Sliders

### ISSUE THREAD

**Issue by sperglord8008s** [TheQwertiest/foo_spider_monkey_panel#178]
I use the playback rate DSP a lot and really like that sliders can be controlled by the mouse wheel but the stepped increments are far to large, Is it possible to make the mouse wheel move the sliders just a tiny bit for each scroll wheel click?

Often software for video and photo editing will have a hotkey to increase the granularity of the mouse-wheel while pressed, its super useful for quick and precise adjustments.

I've already changed windows scroll to a single line both vertically and horizontally, I even changed the registry value for the mouse wheel increment but it has no effect below a setting of 1.

Any help is appreciated

![Foobar2000 Scroll Wheel Increment](https://user-images.githubusercontent.com/54192936/181090358-52a30513-7551-4880-b65c-1fc6e0c98d40.gif)

**Comment by TheQwertiest** [comment]
This issue is not related to SMP as it does not implement native sliders. fb2k board would be a better place to ask this question: https://hydrogenaud.io/index.php?board=28.0
