### ISSUE TITLE
HtmlWindowWithCheckBox.txt sample - utils.CreateHtmlWindow

### ISSUE THREAD

**Issue by smoralis** [TheQwertiest/foo_spider_monkey_panel#18]
You have missed and include in the sample
include(fb.ComponentPath + "docs\\Flags.js");

and to get it to work I needed to increase sleep time 
https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/c135881836a2b613ae28f76efcc1a54cd5302f93/foo_spider_monkey_panel/js_objects/html_window.cpp#L309

**Comment by TheQwertiest** [comment]
Haha, and I've actually put a TODO there regarding this issue...

**Comment by TheQwertiest** [comment]
Should work now (see attachment)
[foo_spider_monkey_panel.zip](https://github.com/TheQwertiest/foo_spider_monkey_panel/files/2437518/foo_spider_monkey_panel.zip)
