### ISSUE TITLE
Blank configuration problem with event handlers

### ISSUE THREAD

**Issue by dima-lur** [TheQwertiest/foo_spider_monkey_panel#181]
I don't know if it's worth opening a bug when it's found in the dev build, but here's one: event handlers (on_size, on_paint) never called in script if you've created a new blank configuration of SMP panel. Аnd they continue to be ignored on subsequent launches of the player, but the text of the script is saved normally.

**Comment by TheQwertiest** [comment]
That's weird, I'll look into it, thanks

**Comment by TheQwertiest** [comment]
I've checked the latest dev build and it seems to work fine: https://ci.appveyor.com/api/buildjobs/n3dwxs7sge90cfw8/artifacts/_result%2FWin32_Release%2Ffoo_spider_monkey_panel.fb2k-component

Artifact publishing for dev builds was broken for quite a while, so perhaps you were using outdated and broken and dev build?

**Comment by dima-lur** [comment]
Hm. My steps are obvious:
1) git clone https://github.com/TheQwertiest/foo_spider_monkey_panel
    cd cd foo_spider_monkey_panel\scripts
    setup.py
2) Run workspaces\foo_spider_monkey_panel.sln with MSVC 2022 17.3.1
3) Select Release Win32 & build
4) Run scripts\pack_component.py
5) Copy _result\Win32_Release\foo_spider_monkey_panel.fb2k-component contents to player;s plugin dir
6) Add SMP panel -> blank white panel

**Comment by TheQwertiest** [comment]
Hm... Can you try the dev build that I've linked above?

**Comment by TheQwertiest** [comment]
And just to make sure, you are on `master` branch, right?

**Comment by TheQwertiest** [comment]
Nevermind, I've reproduced the problem, thanks

**Comment by dima-lur** [comment]
Yeah, master branch by default. 

> 

Same result

**Comment by TheQwertiest** [comment]
Should be fixed now :)
