### ISSUE TITLE
Where did build instructions for mozjs using MSVC++ go?

### ISSUE THREAD

**Issue by AudriusButkevicius** [TheQwertiest/foo_spider_monkey_panel#182]
Stackoverflow post links here, but wiki is gone.

And the project page now talks about clang.

**Comment by TheQwertiest** [comment]
Newer mozjs can't be built with MSVC anymore and can only be built using clang.

The build process for esr68 is described here (it might be outdated though): https://theqwertiest.github.io/foo_spider_monkey_panel/docs/for_developers/building_spidermonkey/

There are no instructions for esr91 yet, but the build process can be reproduced with the following script: https://bitbucket.org/TheQwertiest/mozjs/src/master/build_scripts/setup.py
The script is quite messy, but it does the job :)

**Comment by AudriusButkevicius** [comment]
I'm confused as the es68 build instructions talk about llvm, so I assumed its not usable with msvc.

Re esr91, is that the last version still buildable with msvc? Or is that version used in this project that uses clang?

**Comment by TheQwertiest** [comment]
To clarify:
- if you are talking about MSVS (as in Visual Studio): mozjs is not buildable by VS and I don't think it ever was
- if you are talking about MSVC (as in Visual Compiler): for some time mozjs was buildable by VC, but it was deprecated and now it can only be build by clang. The last ESR that I was able to build with VC was ESR 52

About clang:
- clang does not have anything to do with VS (apart from being an optional installation component)
- clang is a part of LLVM project

**Comment by AudriusButkevicius** [comment]
Sorry, I know my question is very unclear.

Effectively I am after the latest version I can build using msvc (the compiler), as I want to produce a static lib I can link against in my project that uses a recent toolchain, hence I need to build mozjs using a recent toolchain, because seems I can't statically link objects produced by a different toolchain (clang) or even different versioned (v140 vs v142) toolchain.

I know a dll would make it easier, but that sadly doesm't work in my case :(.

I take it last possible version is esr52 and the instructions are as per the link above.

**Comment by TheQwertiest** [comment]
Tbh, I'm not sure if mozjs could be embedded statically at all (I've never tried it).
But yes, your best would be to try esr 52.

> and the instructions are as per the link above.

Instructions above were only tested on esr68, so I'm not sure if it's applicable to esr52. Additionally, you might need to use some of the older versions of MozillaBuild, since the latest one was not compatible even with ESR68.

**Comment by TheQwertiest** [comment]
Oh, and I've found my old instructions for esr60: https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/60cf366fc2437c2ddd0c4f5ac6adc6e227b35f7e/docs/for_developers/building_spidermonkey.md

**Comment by AudriusButkevicius** [comment]
Any clue/recollection of versions of mozbuild for 60? So far that seems to be the biggest sticking point for me.

Also, instructions above suggest esr60 is possible?

Sorry. i know this is turning into a trivia, I'm know its not related to your project, but I suspect the only person on the internet that knows about this 🤣

**Comment by TheQwertiest** [comment]
> Any clue/recollection of versions of mozbuild for 60?

No, sorry. You could try searching and comparing the release dates for esr and mozbuild

> Also, instructions above suggest esr60 is possible?

Yea, it seems, that I've built esr60 with msvc as well

**Comment by AudriusButkevicius** [comment]
Thanks for all the info.
