### ISSUE TITLE
any plans for foobar 2.0

### ISSUE THREAD

**Issue by steve3d** [TheQwertiest/foo_spider_monkey_panel#188]
as foobar 2.0 has released beta 10, some of the official components have been updated to support x64 foobar, but I don't see any update of my favorite component foo_spider_monkey_panel.

So I'm wondering, is there any plans for foobar 2.0 x64 support? When can we see the x64 version?

**Comment by TheQwertiest** [comment]
See https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/209
