### ISSUE TITLE
RunContextCommandWithMetadb always fails

### ISSUE THREAD

**Issue by a1waysbeta** [TheQwertiest/foo_spider_monkey_panel#19]
Error: Spider Monkey Panel v1.0.0 (JS Smooth Playlist by Br3tt aka Falstaff)
'RunContextCommandWithMetadb' failed:
handle argument is invalid

File: jssp.js
Line: 2443, Column: 23

Stack trace:
  oBrowser/this.on_mouse@jssp.js:2443:23
  on_mouse_lbtn_down/timers.mouseDown<@jssp.js:3345:8
___
  Error: Spider Monkey Panel v1.0.0 (JSPlaylist vSMP-Mod by Br3tt)
'RunContextCommandWithMetadb' failed:
handle argument is invalid

File: WSHplaylist.js
Line: 1045, Column: 22

Stack trace:
  oItem/this.check@WSHplaylist.js:1045:22
  oList/this.check@WSHplaylist.js:2235:6
  on_mouse_lbtn_up@main.js:1268:3

**Comment by TheQwertiest** [comment]
Thanks for the report!
See attachment for the version with the fix:
[foo_spider_monkey_panel.zip](https://github.com/TheQwertiest/foo_spider_monkey_panel/files/2439121/foo_spider_monkey_panel.zip)
