### ISSUE TITLE
MF_GRAYED menu does not work in Wine/Linux

### ISSUE THREAD

**Issue by TT-ReBORN** [TheQwertiest/foo_spider_monkey_panel#193]
As title says, if menu item activates MF_GRAYED state, it is not being displayed as MF_GRAYED but displayed as normal state with deactivated additional menu shown if present. 

Test it with my theme: top menu Options > Player controls > Lock player size.
Now Options > Player size and Options > Layout should be grayed out but they are displayed normal.

This happens in Wine, on Windows all is OK.

**Comment by ghuDaYuYu** [comment]
You may try MF_DISABLED | MF_GRAYED to make it work in both platforms

**Comment by TT-ReBORN** [comment]
~Thanks but it does not work.~

**Comment by ghuDaYuYu** [comment]
You´re welcome, thought it used to work as seen for example, in the js-smooth sample component (jssp.js):
`_child01.AppendMenuItem((showInAlbumView ? MF_STRING : MF_GRAYED | MF_DISABLED), 1011, "Highlight in JS Smooth Browser");`

**Comment by TT-ReBORN** [comment]
@ghuDaYuYu,

so I took a closer look and yea **IT DOES WORK** now, needed to adjust another thing in my code! Thanks a lot =)
One more Wine bug fixed ;-)

-TT
