### ISSUE TITLE
Blank S<P

### ISSUE THREAD

**Issue by IPD8WN32** [TheQwertiest/foo_spider_monkey_panel#194]
If I create a new panel anywhere in the UI it instantly crashes with this error:

Error: Spider Monkey Panel v1.6.1 ({150D4953-751F-4C1B-8735-0362DDE8FA11})
GdiDrawText failed:
font argument is null

File: <main>
Line: 65, Column: 8
Stack trace:
  on_paint@:65:8

For clarification, this is on Windows and I've seen someone else post an issue with the same error except on WINE.

**Comment by regorxxx** [comment]
You are missing somehow the default font, and the default script should be checked against this...

Line 65:
```
    if (g_font) {gr.GdiDrawText(g_text, g_font, g_hot ? g_textcolour_hl : g_textcolour, 0, 0, ww, wh, DT_VCENTER | DT_CENTER | DT_WORDBREAK | DT_CALCRECT | DT_NOPREFIX);}
    else {fb.ShowPopupMessage('Missing default font on ' + (g_is_default_ui ? 'DUI' : 'CUI') + '.')}
```

But the script is hardcoded on the DLL.

**Comment by IPD8WN32** [comment]
Yes, you were right the default font wasn't selected. I have fixed it now and it works. Thank you.
