### ISSUE TITLE
Move Callback fires after menu closes when changing focus to another window

### ISSUE THREAD

**Issue by regorxxx** [TheQwertiest/foo_spider_monkey_panel#208]
1. Create menu within panel
2. Alt + tab to other windows, and work on them (wait a few seconds)
3. Alt + tab back to foobar

Result: 
Button remains on focus, because move callback keeps firing on last position even if panel or windows is not on focus anymore. Note window.IsVisible remains true, but that's wrong. Restoring foobar2000 window does not fix it, until mouse reenters the panel.

![bug](https://user-images.githubusercontent.com/83307074/234846914-c521e5bc-0940-471b-9abe-81785a4f4af2.gif)

Button remains on focus (blue) after alt-tab.
![imagen](https://user-images.githubusercontent.com/83307074/234844534-86876055-2b12-4817-86bb-eaec27e73d41.png)

Have added logging to the callbacks: the last ones are after click and alt-tab.
![imagen](https://user-images.githubusercontent.com/83307074/234844579-ddc6eb4b-cf03-4972-bc99-b3ad0bc77aef.png)

@marc2k3 I suppose this also happens on jscript (?)

**Comment by marc2k3** [comment]
Maybe update the state of your button/repaint inside on_mouse_rbtn_up before TrackPopupMenu.

If you right click a hyperlink here on github, it remains underlined while the mouse is down. Release to open the menu and the link is no longer underlined.

**Comment by regorxxx** [comment]
> Maybe update the state of your button/repaint inside on_mouse_rbtn_up before TrackPopupMenu.
> 
> If you right click a hyperlink here on github, it remains underlined while the mouse is down. Release to open the menu and the link is no longer underlined.

Nope. Move callback is called after TrackPopupMenu; that's the thing. It's called multiple times at times I can't define while being on other windows. Check the console at top. The menu is called at click, all the other move strings correspond to SMP firing a callback when foobar is not even visible (so it obviously overrides anything you do at other places). Have you taken a look at the gif? The mouse is released at the click line (and it works fine up to that point). The rest is just things done by SMP without any logic after menu creation and alt-tab.

I have added as a workaround a position cache, so it only refreshes the button if mouse really moves.

**Comment by regorxxx** [comment]
Well... you don't even need to use alt-tab, it's the same for non maximized windows. Just clicking outside foobar triggers the problem:

![bug](https://user-images.githubusercontent.com/83307074/234901118-ea33db20-3d21-48f8-a9c9-76abf47ccfc5.gif)

Note how the button loses focus after clicking the menu as it should be, but once the menu closes due to changing windows, the move callback fires at the last position which is totally wrong.

After adding the move check:
![image](https://user-images.githubusercontent.com/83307074/234902206-0177d51a-46e2-4304-9eba-a7129aae1940.png)
![bug2](https://user-images.githubusercontent.com/83307074/234902509-1b3e570e-0ca6-4476-a69e-4b791ab25b57.gif)

**Comment by marc2k3** [comment]
I really don't understand the mouse move/gifs at all.

But maybe you should change the state of your button from `on_focus` when `is_focused` is `false` ??? This should trigger when you ALT-TAB.

https://theqwertiest.github.io/foo_spider_monkey_panel/assets/generated_files/docs/html/module-callbacks.html#~on_focus

**Comment by regorxxx** [comment]
Focus is related to mouse clicking first, which has nothing to do with move callback firing when a window is not even active. So even if that "fixes" the problem, so does caching the X,Y position and only doing things when such coordinates change. In any case those are workarounds, the move callback is not working as it should be.

I don't understand what you don't understand from my gifs. First one clearly shows a menu opening and the button being activated after closing a menu and changing the active window to another one. That should never happen. The button is not in focus when opening the menu, and the move callback fires when the window is hidden which is a bug.

Second gifs applies a workaround. And it clearly shows what should happen when you alt-tab or switch the active window.

This gif should clearly display the move callback is not working as intended at all. It makes zero sense that moving the mouse outside foobar and clicking again in foobar, outside the panel, fires the move callback withing the panel when the mouse is not there. It just reuses the last known position.

![bug3](https://user-images.githubusercontent.com/83307074/235010213-f3fd2b7e-bd70-438c-b328-eb848be825e8.gif)

**Comment by regorxxx** [comment]
![bug4](https://user-images.githubusercontent.com/83307074/235010329-b0000092-7055-4afe-a4f6-6ac2e14b6bd6.gif)

You don't even need to switch windows, it does the same just by moving the mouse out.

**Comment by marc2k3** [comment]
![mouse](https://user-images.githubusercontent.com/62050527/235013113-57b581e0-dee9-4335-8c0e-16710b33cbc6.gif)

**Comment by regorxxx** [comment]
Never mind, this thing was related to some kind of incompatibility with AutoHotkey which was doing strange things with the callbacks. It seems ok after fixing that.
