### ISSUE TITLE
Symbols now showing correctly 

### ISSUE THREAD

**Issue by gabriels1963** [TheQwertiest/foo_spider_monkey_panel#212]
I have foobar2000 v2.0 in Windows 11 and Windows 10 (exact same copy) with Awesome Font installed on both.
However, in Windows 10 some symbols are not showing correctly as displayed below.
Incorrect symbols:
![Screenshot 2023-05-12 094543](https://github.com/TheQwertiest/foo_spider_monkey_panel/assets/26761237/04365e75-6715-41e8-af29-a998e1e0f6f3)
![Screenshot 2023-05-12 094629](https://github.com/TheQwertiest/foo_spider_monkey_panel/assets/26761237/04c9f7b8-28ce-4e8c-ab94-f3b949b36b62)
![Screenshot 2023-05-12 094748](https://github.com/TheQwertiest/foo_spider_monkey_panel/assets/26761237/c14d3e31-e39c-47ec-b3a8-17ef5473e15d)

Correct symbol:
![Screenshot 2023-05-12 094853](https://github.com/TheQwertiest/foo_spider_monkey_panel/assets/26761237/d43c599a-417e-41da-9634-ca1751abc78a)

**Comment by regorxxx** [comment]
That's not enough info. Which script are you using?

**Comment by gabriels1963** [comment]
> That's not enough info. Which script are you using?

I am using the following and the one in bold is the font problematic one:
Spider Monkey Panel v1.6.1 (Cover art Panel: Cover art Panel v2.0 by Strig): initialized in 27 ms
Spider Monkey Panel v1.6.1 ({53E35428-59A0-4B0C-8B85-0A9F55DF77C5}: Library Tree v2.2.0 by WilB): initialized in 8 ms
Spider Monkey Panel v1.6.1 (Last.fm Bio: Last.fm Bio by marc2003): initialized in 53 ms
Spider Monkey Panel v1.6.1 (Last.fm panel: Allmusic Review by marc2003): initialized in 9 ms
Spider Monkey Panel v1.6.1 (Last.fm Similar Artists + User Charts + Recent Tracks: Last.fm Similar Artists + User Charts + Recent Tracks by marc2003): initialized in 20 ms
Spider Monkey Panel v1.6.1 (Last.fm panel: Last.fm panel v2.0 by Strig): initialized in 23 ms
Spider Monkey Panel v1.6.1 (Strig UI Control Panel: Strig UI Control Panel v2.1 by Strig): initialized in 18 ms
**Spider Monkey Panel v1.6.1 (JSPlaylist: JSPlaylist vSMP-Mod by Br3tt): initialized in 1777 ms**
Spider Monkey Panel v1.6.1 (Track info panel: Track info panel v2.0 by Strig): initialized in 9 ms

**Comment by gabriels1963** [comment]
Found the missing fonts
