### ISSUE TITLE
Crashes, list.blacklist is undefined

### ISSUE THREAD

**Issue by dreidelman** [TheQwertiest/foo_spider_monkey_panel#217]
Error: Spider Monkey Panel v1.6.1 (Biography: Biography v1.2.3b21 by WilB)
list.blacklist is undefined

File: images.js
Line: 280, Column: 3
Stack trace:
  blacklist@images.js:280:3
  blackListed@images.js:287:30
  loadStndCov@images.js:1149:12
  on_get_album_art_done@images.js:1223:8
  on_get_album_art_done@callbacks.js:46:6

**Comment by dreidelman** [comment]
lmao i just deleted the entire blacklist and that fixed 👍

**Comment by TheQwertiest** [comment]
This repo does not offer support for problems in 3rd party scripts (unless they are caused by component itself).
Please, use corresponding support threads ([hydrogen](https://hydrogenaud.io) in this case).
