### ISSUE TITLE
This component was built for a different processor architecture

### ISSUE THREAD

**Issue by aubreyz** [TheQwertiest/foo_spider_monkey_panel#223]
When I try to install latest version (I have never tried to use before) I get error 

"This component was built for a different processor architecture"

Using foobar2000 2.0 x64

Not working on 64bit?????

Looks like a great plugin -- how to get it to work??

**Comment by GintTech** [comment]
Same issue, Windows 11 Pro 64-bit, Build 22621.2428
                    Intel Core i5 12400

**Comment by TT-ReBORN** [comment]
You guys have installed foobar in 64-Bit and the Spider Monkey Panel component is only compatible with 32-bit foobar. 
The upcoming Spider Monkey Panel v2 has [64-bit in its roadmap](https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/213).

**Comment by TheQwertiest** [comment]
Exactly as TT said, SMP does not have 64bit version yet (https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/209).
