### ISSUE TITLE
UIHacks controls doesn't work anymore

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#24]
Hi,
I just updated some of my scripts from jscript panel to your spider_monkey one. It seems to be quite a big improvement in term of speed. The memory usage is higher though, but it doesn't matter on my computer, it's not a major increase. Maybe it's because of all the xxx.Dispose() calls which i had to remove ?
However, some of the commands for controling the UI Hacks component don't work anymore. I didn't test them all, most commands still work, but UIHacks.MaxSize = true , UIHacks.MinSize = true doesn't work, so the code below doesn't work anymore (it allow to set a maximum or minimum size for the main window, so using that, it was possible to control/change the window size from a button)

var UIHacks = new ActiveXObject("UIHacks");
UIHacks.MaxSize=false;
UIHacks.MinSize=false;

**Comment by TheQwertiest** [comment]
It's still working, you have to use `UIHacks.MaxSize.Enabled=false` instead.
`Enabled` is actually the proper way, and it was working in JScript only because of COM interface shenanigans =)

**Comment by TheQwertiest** [comment]
Also, `Dispose` calls are not needed anymore (and they were removed from API as well), since JS engine can GC them by itself.

**Comment by Ottodix** [comment]
Okey, i fixed all my issues, thanks!
Actually, i had another issue related to this more efficient garbage collector, which i managed to fix by myself: now, when you share big object through NotifyOthers, you can't simply get them through  on_notify_data(name, info), they get lost in the process. Maybe because the object info is destroyed at the end of the callback, i don't know, but i managed to fix the issue using functions which clone the info object (and then i can use the cloned object).

Again, thanks for your work

**Comment by TheQwertiest** [comment]
Uh, actually I've documented this behavior(and more) in [Callbacks.js](https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/master/component/docs/Callbacks.js), but forgot to duplicate in API changes... Sorry for that -_-
