### ISSUE TITLE
utils.ReadTextFile doesn't properly read certain files

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#26]
// utils.ReadTextFile doesn't properly read certain files, e.g. UCS-2LE BOM (that's what notepad++ reports)

// TESTS:

// a) Test with a file written using utils.WriteTextFile: all OK

var t1 = [{"test1": "test1"},{"test2": "test2"}];
var p1 = fb.ProfilePath + "Test.json"
utils.WriteTextFile(p1, JSON.stringify(t1))
console.log("p1", "!!!" + utils.ReadTextFile(p1) + "!!!");
console.log(JSON.parse(utils.ReadTextFile(p1)));

// b) Test with a file written using the original text save method: problems:

// 1) If it's a json file, JSON.parse fails & crashes
// 2) If it's a text file, extra unwanted line at end
// 3) Effects any static json or text files written with the original text save method & not since updated
// 4) It seems that utils.ReadTextFile in SMP doesn't properly handle UCS-2LE BOM which the original text save method seems to create
// 5) All OK in JScript panel

var t2 = [{"test3": "test3"},{"test4": "test4"}];
var p2 = fb.ProfilePath + "Test_.json";
var fso = new ActiveXObject("Scripting.FileSystemObject")
// original text save method:
var save = function(l, n) {try {var ts = fso.OpenTextFile(n, 2, true, -1); ts.WriteLine(l); ts.Close(); return true;} catch (e) {return false;}}
save(JSON.stringify(t2), p2);
console.log("p2", "!!!" + utils.ReadTextFile(p2) + "!!!");
console.log(JSON.parse(utils.ReadTextFile(p2))); // CRASH in SMP (JSP OK)

**Comment by TheQwertiest** [comment]
Just FYI: UCS-2LE BOM is actually UTF-16LE BOM =)

**Comment by TheQwertiest** [comment]
Does it actually crash for you or is it just a SMP error like `JSON.parse: unexpected non-whitespace character after JSON data at line 2`?

**Comment by Wil-B** [comment]
Yes the example above gives a full crash + that message:

Error: Spider Monkey Panel v1.0.3 ({735AA13A-75AB-4867-9E30-B396829F70BD})
JSON.parse: unexpected non-whitespace character after JSON data at line 2 column 1 of the JSON data

File: <main>
Line: 20, Column: 13

Stack trace:
  @<main>:20:13

**Comment by TheQwertiest** [comment]
Anyways, I've fixed it. You can try it out by using [latest build](https://ci.appveyor.com/api/projects/theqwertiest/foo-spider-monkey-panel/artifacts/_result%2FWin32_Release%2Ffoo_spider_monkey_panel.fb2k-component?branch=master&job=Configuration%3A%20Release).
