### ISSUE TITLE
plman.PlayBackOrder always returns undefined?

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#27]
function on_playback_order_changed(new_order_index) {
console.log("SMP new_order_index: " + new_order_index);
console.log("SMP (callback) plman.PlayBackOrder: " + plman.PlayBackOrder)
}

console.log("SMP (initialisation) plman.PlayBackOrder: " + plman.PlayBackOrder)

JSP works correctly with the above test.

Thanks for the fix of utils.ReadTextFile. It seems to be fine now.

**Comment by TheQwertiest** [comment]
It is `plman.PlaybackOrder`, not `plman.PlayBackOrder` =)
ECMAScript (and thus JavaScript) is case-sensitive, Microsoft just ignored this rule when making JScript.

**Comment by Wil-B** [comment]
Ah thanks! It's working now. I spotted other case-sensitive issues but missed that one!
