### ISSUE TITLE
Broken properties in PlaylistRecyclerManager

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#28]
Functionality is incomplete...

First you need to delete a playlist so there is at least something with a valid index to access...

```js
var r = plman.PlaylistRecyclerManager; // OK
console.log(r.Count); // OK
console.log(r.Name(0)); // 'get_Name' failed: Invalid number of arguments
var handles = r.Content(0); //'get_Content' failed: Invalid number of arguments
```

The `Restore` and `Purge` methods work fine.

Personally, I wish I'd really took notice of this before all my breaking changes in v2 and refactored it then. The idea of supplying `arguments` to a `property` doesn't make any sense! :/

I think it would be much better nuking the whole interface and making them fixed methods something like...

```js
plman.RecyclerCount; // OK this is a property, like PlaylistCount
plman.GetRecyclerItems(index);
plman.GetRecyclerName(index);
plman.RecyclerPurge(affectedItems);
plman.RecyclerRestore(index);
```

**Comment by marc2k3** [comment]
I've actually made the changes I was thinking of but I'm not really sure if it's going to see the light of day or not. 

https://github.com/marc2k3/foo_jscript_panel/commit/43a25d2f2785942791dae8f283a61b3db09b725a

There's not much point continuing with JSP now... :P

**Comment by TheQwertiest** [comment]
Heh, missed that one.

Ideally, I would've liked to make a separate `FbRecycledPlaylist` object, which could be fetched via array accessory `plman.PlaylistRecyclerManager[i]`. Regretfully, this doesn't mesh well with underlying fb2k api...

I would rather keep all Recycler methods under a separate `PlaylistRecyclerManager` though, since `plman` is pretty big as it is. 

PS: I'm thinking of renaming it to `PlaylistRecycler` or just `Recycler`, since it has to be rewritten anyway. Not sure which one to choose though.

**Comment by marc2k3** [comment]
I won't start a new issue for it but I can reproduce the Menu Manager bug reported in your thread on HA - even with the latest build from appveyor. Make sure you're actually selecting a Columns UI layout preset. I guess it's different from most menu commands because they're dynamically generated. Other menu commands work fine. The original code was added by the WSH panel mod author and I don't know anything about it - except it works.

[crash reports.zip](https://github.com/TheQwertiest/foo_spider_monkey_panel/files/2478976/crash.reports.zip)

**Comment by TheQwertiest** [comment]
Should be available via [latest build](https://ci.appveyor.com/api/projects/theqwertiest/foo-spider-monkey-panel/artifacts/_result%2FWin32_Release%2Ffoo_spider_monkey_panel.fb2k-component?branch=master&job=Configuration%3A%20Release), once it's finished.

**Comment by marc2k3** [comment]
Nice. I'm leaving JSP as it is - in fact the repo is in archive mode now. Everything is still available - it's just read-only.

**Comment by TheQwertiest** [comment]
Just don't remove it, please! I'm using it fairly regularly to find regressions in my code =)
