### ISSUE TITLE
Out of memory issue.

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#32]
Hi, 

With the lastest release, a panel using too much memory seems to crash. I used to do a cover cache, i can't do it anymore with the lastest release. Here is a example of code which always crash on my setup, it create a array containing the covers of the 2000 first tracks, grabbed with utils.GetAlbumArtV2: 

```
var nb_of_covers = 2000;
var image_cache = Array();
var populate_covers_timer = Array();
var FullLibraryList = null;

function populate_with_library_covers(start_items){	
	if(start_items == 0){
		FullLibraryList = fb.GetLibraryItems(); start_items = 0;			
		gTime_covers = fb.CreateProfiler();			
	}		
	var current_item = start_items;
	gTime_covers.Reset();		
	var total = FullLibraryList.Count;
	while(current_item < total){
		if(current_item < nb_of_covers){
            image_cache[current_item] = utils.GetAlbumArtV2(FullLibraryList[current_item]);            
		}
		current_item++;
		//Set a timer to avoid freezing on really big libraries
		if(current_item%250 == 0 && gTime_covers.Time > 100){		
			populate_covers_timer[populate_covers_timer.length] = window.SetTimeout(function(){
				window.ClearTimeout(populate_covers_timer[populate_covers_timer.length-1]);
				populate_with_library_covers(current_item);
			}, 25);				
			return;
		} 				
	}
}	
populate_with_library_covers(0);
```

Error message: 
`Error: Spider Monkey Panel v1.0.4 ({9B3A2903-6468-463C-8579-15BBC1C4738F})
Out of memory: 1020262025/1000000000 bytes`

**Comment by TheQwertiest** [comment]
Well, this panel uses up 1GB worth of memory :\\
IMO, you should just resize image to smth adequate to reduce RAM usage. But if you really want to use full sized images you can increase maximum allowed heap through advanced settings: `Preferences`>`Advanced`>`Tools`>`Spider Monkey Panel`>`Maximum heap size`.

**Comment by TheQwertiest** [comment]
PPS: `Maximum heap size` is the only *safe* setting in `Advanced` settings, I don't recommend changing anything else, since it might impact your panel performance hard in really unexpected ways.

**Comment by TheQwertiest** [comment]
PPPS: The limit is per process, not per panel, so adjust accordingly.

**Comment by Ottodix** [comment]
Thanks!
On this code which isn't optimized at all, yes, it uses a lot of memory. But on my real code which is a lot more complicate, it load a smaller version of the covers little by little without freezing foobar, and it uses around 150Mo (for 3000+ albums). On my computer, the increase of ram is completely okey, and i can navigate between albums without any loading time for the covers.
I increased this Maximum heap size, now i don't have crash anymore, but the images are lost between panels, i used to send this array of covers from one panel to another using on_notify_data and a deep clone of the received object, but the resulting images are now... corrupt ? I don't know exactly, but gr.DrawImage() now crash with them (DrawImage failed: Object is not of valid type)

So for the moment, i can't use this new version if i want to keep this cover cache :/

**Comment by TheQwertiest** [comment]
> it uses around 150Mo

It uses MUCH more. Images are not stored in your usual memory (i.e. the one that you can see via Task Manager), but rather kernel memory which is not counted towards fb2k memory usage (but counts towards total RAM usage). E.g. when your panel OOM'd the task manager might've displayed smth around 200mb usage in fb2k, but total RAM usage would've been 1.2Gb.

>  i used to send this array of covers from one panel to another using on_notify_data

You can't do this on SMP, this is engine limitation: see [docs](https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/master/component/docs/Callbacks.js#L136) for details.

**Comment by TheQwertiest** [comment]
On another note: one of the features that I'm working on might enable the `deep clone` of some native objects (like GdiImage). So your scenario might be possible in the future.

**Comment by TheQwertiest** [comment]
> Then i'll keep the first version of SMP

Well, native object transfer via `NotifyOthers` was never possible on SMP, so using first version won't help in your case  :\\
And I strongly advise against using the first version, since it has a lot of bugs that were fixed in the latest version: [CHANGELOG](https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/master/CHANGELOG.md)

**Comment by Ottodix** [comment]
It is working, i use NotifyOthers() in order to send an array of GdiImage(), and i receive the array with on_notify_data(name,info) using images = iterationCopy(info)

Where iterationCopy is this function
`function iterationCopy(src) {
  let target = {};
  for (let prop in src) {
    if (src.hasOwnProperty(prop)) {
      target[prop] = src[prop];
    }
  }
  return target;
}`

Why did it break with the new version, or why did it work with the first one, i don't know, but it work :)

**Comment by TheQwertiest** [comment]
> So your scenario might be possible in the future.

Done! Added constructors in the latest version, so your scenario is possible now (you still have to increase heap limit via advanced settings though): you can deep-copy image objects with the following code `let copy_img = new GdiBitmap(image_from_notify);`.
