### ISSUE TITLE
Memory handling

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#35]
Memory handling in SMP has changed compared with JSP, yet scripts are in the dark over the SMP memory status. The particular problem is ensuring OOMs can't be triggered on systems with low amounts of RAM (perhaps as little as 250MB for all SMP panels) while allowing those with plenty of RAM allocated to SMP to use it. Perhaps "% SMP memory used", which could be dynamically called,  or other SMP memory info could be provided to scripts?

**Comment by TheQwertiest** [comment]
Well, I thought of that, but what could the end user (e.g. you) do with this information?

**Comment by Wil-B** [comment]
Some of my scripts use a dynamic image cache.

So something like:
```
if ("% SMP memory used" < 50) add_img_to_cache();
else trim_img_cache() then add_img_to_cache();
```
Alternatively, but perhaps less effective, would be to know the maximum heap size. Then:
1) Set a limit to the image cache size, e.g. 10-20% of maximum heap size.
2) Script keeps a running total of the size of the image cache in memory.

Then something like:
```
if (image_cache_size_in_memory < allowed_image_cache_size) add_img_to_cache();
else trim_img_cache() then add_img_to_cache();
```
