### ISSUE TITLE
Typos can cause foobar2000 crashes

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#42]
I've had a fair number of foobar2000 crashes due to typos that I would have expected to have been caught as script errors. I'm not sure when this issue was introduced, but I think it used to be OK. It at least effects 1.1.1 & 1.1.2-beta. It might have something to do with setTimeout (or window.SetTimeout) & possibly various other things, since straightforward script errors are caught. If you can't reproduce I can post crash logs.

Example code that crashes foobar2000:

```
function test() {
    var filtr /*typo should be filter*/ = ["1"]; for (var r = 0; r < 1; r++) {console.log("filter[r]", filter[r]);}
}
window.SetTimeout(function() {test();}, 500); // setTimeout same issue
// for me, the code above results in SMP crashing foobar2000
// typo isn't caught as script error
// JSP gives expected script error
```

**Comment by TheQwertiest** [comment]
Yeah, it's a regression, since I've tested specifically this scenario a few versions back

**Comment by TheQwertiest** [comment]
Thanks for the bug report =)

**Comment by TheQwertiest** [comment]
Should be fixed in the latest build, once it's available
