### ISSUE TITLE
utils.ReadTextFile script error

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#43]
If the text file is empty and written without BOM then utils.ReadTextFile gives a script error. JSP OK.

Example code that illustrates the issue on my machine is below.

```
var fn = "C:\\temp\\test11.txt";
utils.WriteTextFile(fn, "", false); // script error
//utils.WriteTextFile(fn, "1", false); // OK
//utils.WriteTextFile(fn, "", true); // OK
var readFile = utils.ReadTextFile(fn);
console.log("readFile",readFile);
```
Error:
```
Error: Spider Monkey Panel v1.1.2-beta ({E1DBA06B-4396-41B4-B2A6-7C667D26C114})
ReadTextFile failed:
Internal error: CreateFileMapping failed for `C:\temp\test11.txt`

File: <main>
Line: 5, Column: 16

Stack trace:
  @<main>:5:16
```
Normally I wouldn't write such files. However, I originally obtained the error when a USB drive became full. So instead of the actual text written with BOM it seems it ended up as "" without BOM & the utils.ReadTextFile script error. As an alternative to a fix I could use try catch etc.

**Comment by marc2k3** [comment]
I had a quick at the code and it's a lot stricter. It seems you have to check the file exists AND the filesize is more than zero bytes. WSH/JSP would silently return an empty string on non existent/empty files.

I suppose it is mentioned in the change log in a non-specific way!!

> More rigorous error checks.

**Comment by TheQwertiest** [comment]
@Wil-B thanks for the bug report! =)

@marc2k3 
> I suppose it is mentioned in the change log in a non-specific way!!

Haha, it's rather in the following hidden (but ever present) changelog line:
- Added more bugz...

Anyway, this is a bug: `ReadTextFile` should work properly even with empty file (the file itself should exists though).

Happy New Year, guys! 🎄🍻

**Comment by TheQwertiest** [comment]
Should be fixed in the latest nightly (once it's built).
