### ISSUE TITLE
How to use UIHacks integrated functionalities

### ISSUE THREAD

**Issue by cerbaire** [TheQwertiest/foo_spider_monkey_panel#44]
I read a few month ago that you have integrated some UIHacks functionalities. Are the functionalities documented? How to use them?
Thanks for your support and this great plug-in. 
Nicolas

**Comment by TheQwertiest** [comment]
> I read a few month ago that you have integrated some UIHacks functionalities

You've misread =)
Porting UIHacks functionality is on my TODO list, but nothing's done yet (see https://github.com/TheQwertiest/foo_spider_monkey_panel/projects/1#card-13051369)

**Comment by cerbaire** [comment]
Ah! Yes, I read correctly but just don't remember it a todo.
Thanks.
