### ISSUE TITLE
Custom image is resized on fb.DoDragDrop if it's too small

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#46]
If the provided gdiBitmap is smaller than approx 100px, it will be extended and will look blurred (quite a minor issue though)

**Comment by TheQwertiest** [comment]
Yeah, probably it'll be better to leave image as it is if it's smaller then the drag-window.

**Comment by Ottodix** [comment]
And eventually the opacity of the custom image, could it be just the opacity of the GdiBitmap provided ? Like that we could choose exactly the effect we want. (really not a priority ! It's quite fine already)

**Comment by Ottodix** [comment]
(by quite fine, i mean, quite great : )

**Comment by Ottodix** [comment]
(oups, sorry, i closed this ticket accidentally... ok i stop saying and doing useless things now : )

**Comment by TheQwertiest** [comment]
> And eventually the opacity of the custom image

But you can already do that via many different ways :D
For example:
```javascript
var transparent_img = MAH_IMAGE.ApplyAlpha(70);
var effect = fb.DoDragDrop(
    window.ID, 
    metadb_list, g_drop_effect.copy | g_drop_effect.move | g_drop_effect.link, 
    { custom_image: transparent_img, use_album_art: false }
);
...
```

**Comment by TheQwertiest** [comment]
You can edit the image however you like before supplying it to `fb.DoDragDrop` =)

**Comment by TheQwertiest** [comment]
> Yep, but there is always a minimum transparency so you can't have a zone totally opaque

This is caused by Windows theme (i.e. it's always slightly transparent). You can disable it via options, but that will remove the default drag window background image as well.
