### ISSUE TITLE
CreatePopupMenu() blocks execution of callbacks and setInterval functions

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#48]
Hello, 
I guess the title describe everything. I didn't check all callbacks, i checked on_playback_time, after seeing that all animations seems frozen when i do a right clic on any of my scripts.

I checked also a setInterval function, which isn't executed anymore.

It look like those functions calls are simply delayed until the menu is closed

**Comment by TheQwertiest** [comment]
Yup, that's a bug (same as https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/37). Will be fixed soon =)
Thank for the bug report!

**Comment by marc2k3** [comment]
This fix is incomplete. It only works when using a custom menu - not the default one which I believe is triggered here...

https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/ae2b30145e260ec4d37ec58bd19219252edf724f/foo_spider_monkey_panel/js_panel_window.cpp#L995
