### ISSUE TITLE
dev guide - python requirement

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#5]
There is no mention of the python requirement for the batch file that prepares scintilla and removes the unused lexers from the make file. It was the only hiccup I ran into while building but I just edited the files manually because I already have previous experience with it.

**Comment by TheQwertiest** [comment]
Oh, forgot about that, thanks!

**Comment by TheQwertiest** [comment]
Fixed: https://github.com/TheQwertiest/foo_spider_monkey_panel/wiki/Building-component

**Comment by TheQwertiest** [comment]
Btw, do you mind if I rip pages from your wiki?

**Comment by marc2k3** [comment]
Well there's barely anything there but help yourself.
