### ISSUE TITLE
on_mouse_move when outside of foobar window

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#55]
Hi!

Not really a bug, just a small limitation (maybe something which can't be fixed?): when you click but don't release the mouse button, on_mouse_move is called as long as your cursor is inside foobar window, but not anymore when it goes outside. 

So when you are "dragging" something, a scrollbar for ex, it stops working when you move the cursor outside of foobar, which isn't a standard behavior.

It's clearly not hyper-annoying, but i though that reporting it doesn't hurt : )

**Comment by TheQwertiest** [comment]
Not sure what you mean, it already works (i.e. `on_mouse_move` receives calls as long as mouse button is held down). Examples include @Wil-B 's scripts (Library Tree, YT Track Manager) and scripts from my CaTRoX theme.

<details><summary>Gif</summary><p>

![drag](https://user-images.githubusercontent.com/4470278/51917887-9119fa00-23f1-11e9-8b1f-5c56f3ce4bd7.gif)
</p></details><br>

**Comment by marc2k3** [comment]
I doubt you're using my samples but reading this has made me realise there is a bug in my seekbar/volume objects. By design, my seekbar/volume objects are designed to keep "hold" on while the mouse is within 200 pixels of the defined rectangle and they release if you move your mouse outside. Due to my stupidity, it only works to the left and above the rectangle. The mouse is lost immediately if you move below the bottom or to the right.

Fix- https://github.com/marc2k3/smp_2003/commit/59b491465b6d9ecd7cf1756636394caa554ee234

**Comment by Ottodix** [comment]
Ok, sorry, i found why it doesn't work on mine, it's related to UIhacks, when the frame style is set to "no border". So it's not related to SMP, the issue seems to be there with all columnUI components

**Comment by TheQwertiest** [comment]
@marc2k3 yup, I've seen them (I monitor most of your commits :P). Thanks!

@Ottodix You can work around that problem by enabling/disabling sizing through UIHacks. Here is the way I've done it:
Methods for sizing handling:
https://github.com/TheQwertiest/CaTRoX_QWR/blob/master/theme/Scripts/Common.js#L369
https://github.com/TheQwertiest/CaTRoX_QWR/blob/master/theme/Scripts/Common.js#L382
Sizing handling:
https://github.com/TheQwertiest/CaTRoX_QWR/blob/master/theme/Scripts/Panel_Playlist.js#L173
https://github.com/TheQwertiest/CaTRoX_QWR/blob/master/theme/Scripts/Panel_Playlist.js#L193

Note: in my theme there is a 2-4px padding between the border and panel, which is used for window sizing. So, if there is no padding in your configuration, then you'll have to take it in account when enabling/disabling sizing.

**Comment by Ottodix** [comment]
Thanks ! I implemented something using this enabling/disabling sizing solution, it work great : )
