### ISSUE TITLE
on_mouse_leave (on_focus) event stops to occur after some actions

### ISSUE THREAD

**Issue by 5r-kocm** [TheQwertiest/foo_spider_monkey_panel#60]
Hi.
I'm using foobar2000 1.4.2 with latest stable SMP under WINE (4.2 with gdiplus, vcrun2017 winetricks)
I made a volume control with an illuminated knob while hovering the mouse over SMP area.
Everything works well until I move cursor out of the panel area while holding mouse button pressed.
After that on_mouse_leave (on_focus) event stops to occur and my volumebar always stays highlighted.
Other functionality remains normal.

PSS $imagebutton and builtin columnsui buttons panel act as expected in the same conditions. 
Tested on wsh_panel_mod / jscript_panel with the same result. 
Maybe additional check is required when tracking system mouse events ?

Tested in virtualbox with WIN7 and everything works as expected.

highlighted when on_mouse_move occurs:

![shot1](https://user-images.githubusercontent.com/48093037/53572819-547b2300-3b96-11e9-969f-d2d120643a43.png)

not highlighted when on_mouse_leave occurs:

![shot2](https://user-images.githubusercontent.com/48093037/53572820-547b2300-3b96-11e9-8893-7af7760dca71.png)

cursor outside the panel while holding mouse button:

![shot3](https://user-images.githubusercontent.com/48093037/53572821-547b2300-3b96-11e9-9a7e-0eab875d88da.png)

on_mouse_leave event stops to occur:

![shot4](https://user-images.githubusercontent.com/48093037/53572823-547b2300-3b96-11e9-8805-afe0fa631c24.png)

my volume panel:

[volumebar_panel.zip](https://github.com/TheQwertiest/foo_spider_monkey_panel/files/2915367/volumebar_panel.zip)

**Comment by TheQwertiest** [comment]
Not sure if anything can be done about it (might just a bug in WINE), but I'll look into it =)

**Comment by TheQwertiest** [comment]
> Tested on wsh_panel_mod / jscript_panel with the same result.

Do you mean that it works properly in those components or that it's not working there as well?
And what is the panel UI that you are using? CUI or DUI?

**Comment by TheQwertiest** [comment]
> After that on_mouse_leave (on_focus) event stops to occur ...

Do you mean that both `on_mouse_leave` and `on_focus` events stop working? What about other mouse events (e.g. `on_mouse_move`,`on_mouse_lbtn_down`)? Do they stop working as well?

**Comment by 5r-kocm** [comment]
Вы не против если мы начнём обсуждать баг на русском языке ?
А то на английском возникает некоторое недопонимание :)

**Comment by 5r-kocm** [comment]
Yes, both events stop happening.
on_mouse_move, on_mouse_lbtn_down, on_mouse_lbtn_up, on_mouse_wheel continue to work.

**Comment by TheQwertiest** [comment]
> Sorry, but do you happen to speak Russian?

I do =)

> Only `on_mouse_leave` stops happening

It's most likely a bug in WINE: `WM_MOUSELEAVE` message (which triggers `on_mouse_leave`) is sent by the parent window if it's tracking was requested by `TrackMouseEvent(..., TME_LEAVE, ...)` (like this https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/e26acb380f6ee814e88b9c3085c2b0de8353fba2/foo_spider_monkey_panel/js_panel_window.cpp#L1351). After the mouse leaves the window the mouse event tracking is reset to default values, so we have to set it with `TrackMouseEvent` again. It seems that WINE is not handling the second invocation of `TrackMouseEvent` correctly, thus no more `WM_MOUSELEAVE` messages.

I've never delved into WINE source though, so everything above are just assumptions =)

**Comment by 5r-kocm** [comment]
Я согласен что вайн делает некоторые вещи немного по другому, но родные панели ColumnsUI (например Buttons) в подобной ситуации работают нормально. Я далёк от програмирования на си, но если есть желание можно глянуть гдето здесь:
https://github.com/wine-mirror/wine/blob/master/dlls/user32/input.c

**Comment by 5r-kocm** [comment]
Отправил багрепорт в багзиллу вайна. Не очень надеюсь на результат :) Некоторые баги там висят годами без изменений.

**Comment by TheQwertiest** [comment]
Я пока затрудняюсь ответить в чём источник проблемы - косяки WINE или некорректное использование WinAPI в SMP (которое работает только потому что Microsoft добавило какие-то свои недокументированные костыли, чтобы поддерживать такие сценарии). 
Займусь данной проблемой поплотнее после фиксов GC.

**Comment by TheQwertiest** [comment]
@5r-kocm might be fixed in the dev build
