### ISSUE TITLE
SMP 1.0.4 and higher causes foobar2000 process hang on exit

### ISSUE THREAD

**Issue by 5r-kocm** [TheQwertiest/foo_spider_monkey_panel#61]
On Windows 7 SMP 1.0.4 and higher causes foobar2000 process hang on exit.
Have to kill foobar2000.exe process manually.

Tested in virtualbox on both 32 and 64 bit oses.
Also tested on real hardware with the same behavior.

**Comment by TheQwertiest** [comment]
Could you create a memory dump which is captured during the freeze/deadlock?

## How to create a memory dump

Once fb2k freezes/deadlocks:
1. Launch task manager (`CTRL-SHIFT-Escape`).
2. Click on `Details` tab.
3. Right-click on foobar2000.exe process > `Create Dump File`
</p></details><br>

Post the resulting `*.dmp` file on the sharing service of your choice.

**Comment by 5r-kocm** [comment]
Ok, here it is
https://drive.google.com/file/d/1JXKwFcVzu87u9TAyizHD0RuX1EqMQbdS/view?usp=sharing

**Comment by 5r-kocm** [comment]
By the way, latets version of Jscript Panel also hangs my foobar on win7.

**Comment by TheQwertiest** [comment]
Thanks!
Hm, it seems that both `foo_spider_monkey_panel.dll` and `mozjs.dll` were unloaded at the time of the freeze, so this might not be actually caused by SMP.
Could you try removing the `foo_input_monkey` component and see if freeze comes up again? If it does, please, make and post a new dump.

**Comment by 5r-kocm** [comment]
Still freezes without monkeys audio decoder:
https://drive.google.com/file/d/1o4OITTxqh_1Y22s5cM5YiJYyuNpGKZBl/view?usp=sharing

**Comment by 5r-kocm** [comment]
Tried on a clean 1.4.2 install with latest CUI, panel stack splitter, SMP.
Added SM panel, and foobar hung on exit.

Dump on clean install:
https://drive.google.com/file/d/1iRkATNM5E9XPC9xpVGL5Akwr__1JvIeY/view?usp=sharing

**Comment by TheQwertiest** [comment]
> Tried on a clean 1.4.2 install with latest CUI, panel stack splitter, SMP.

Thanks! This helps a lot! I'll look into it =)

**Comment by TheQwertiest** [comment]
Should be fixed in the latest build, once it's done building

**Comment by TheQwertiest** [comment]
[latest build]: https://ci.appveyor.com/api/projects/theqwertiest/foo-spider-monkey-panel/artifacts/_result%2FWin32_Release%2Ffoo_spider_monkey_panel.fb2k-component?branch=master&job=Configuration%3A%20Release

**Comment by 5r-kocm** [comment]
Hangs are gone, thank you. Maybe you can fix #60 :)
