### ISSUE TITLE
Properties setting incorrectly

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#64]
I've had this issue with the latest beta's:

```
window.GetProperty("bla", "string") // open properties & change string to text: sets: true
window.GetProperty("bla1", true) // open properties & change true to false: sets: 0
window.GetProperty("bla2", false) // open properties & change false to true: sets: -1
```

**Comment by TheQwertiest** [comment]
Thanks for the bug report! Should be fixed now (once the new build is ready).

**Comment by Wil-B** [comment]
Thanks for the fix. But there seems to be a minor issue with trailing zeroes being added to numbers entered with a decimal point. If it's intended new behaviour then it doesn't really matter...

```
window.GetProperty("0.8",0.8) // Sets: 0.8000000000000000 // previously would be set as 0.8
window.SetProperty("0.9",0.9) // Sets: 0.9000000000000000 // previously would be set as 0.9
window.GetProperty("1",1) // Sets: 1 OK
window.SetProperty("1.2",1.2) // Sets: 1.200000000000000 // previously would be set as 1.2
```

**Comment by TheQwertiest** [comment]
It's not really a bug, but yea, it looks nicer without trailing zeroes - I'll see what can be done about it.

**Comment by TheQwertiest** [comment]
Rectified in https://github.com/TheQwertiest/foo_spider_monkey_panel/commit/8aba0a207dd42347b47b74b6f037993e04890366

**Comment by Wil-B** [comment]
Thanks. Unfortunately I wasn't able to test the fix, as it crashes when trying to open properties.

Fresh portable install + 1 SMP panel.

Enter:

```
window.GetProperty("0.8", 0.8);
```
Close configure and try & open properties.

Crashes: 
[Properties crash.zip](https://github.com/TheQwertiest/foo_spider_monkey_panel/files/3102890/Properties.crash.zip)

**Comment by TheQwertiest** [comment]
Fixed crash in https://github.com/TheQwertiest/foo_spider_monkey_panel/commit/d1b1a909932121191ef37e539c461c8c4e62fd2d .
Will fix the trailing zeroes later.
