### ISSUE TITLE
window.PanelMemoryUsage & window.TotalMemoryUsage: discrepancy

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#65]
In particular, window.PanelMemoryUsage seems to be under reporting.

Example:

Use a layout with ONE SMP panel & insert the code below.
Play a track to compare memory use.

```
let str = "With a single SMP panel, I would have thought window.PanelMemoryUsage & window.TotalMemoryUsage should be about the same. Although, window.PanelMemoryUsage seems correct for images (not shown), it doesn't seem to be taking into account certain other things."
let arr = [];
for (let i = 0; i < 642000; i++) arr.push(str + " - " + Math.random())

function on_playback_new_track() {
    console.log("window.PanelMemoryUsage: " + window.PanelMemoryUsage + " bytes; arr.length: " + arr.length);
    console.log("window.TotalMemoryUsage: " + window.TotalMemoryUsage + " bytes; arr.length: " + arr.length);
}
```
Values on my device for this example are:
window.PanelMemoryUsage: 168 bytes
window.TotalMemoryUsage: 31637652 bytes

While window.PanelMemoryUsage seems correct for images (not shown), it doesn't seem to be taking into account certain other things, at least on my device.

**Comment by TheQwertiest** [comment]
That's the intended behaviour - memory usage consists of two parts:
- My custom JS objects, which have memory tracking (e.g. GdiBitmap, FbMetadbHandle, FbProfiler) - counted towards `PanelMemoryUsage` and `TotalMemoryUsage`.
- Native JS objects (e.g. arrays, strings, functions) - counted only towards `TotalMemoryUsage`.

There is no (affordable) mechanism to make a relation between a native JS object and a panel in which it was created, thus it's impossible to differentiate the memory allocation between different panels.
