### ISSUE TITLE
DrawImage cant handle images' alpha correctly

### ISSUE THREAD

**Issue by elia-is-me** [TheQwertiest/foo_spider_monkey_panel#70]
![Snipaste_2019-04-20_12-04-48](https://user-images.githubusercontent.com/5344103/56452595-e4eb0e00-6364-11e9-919e-ee0a498819da.png)

the grey icon became black in smp.

**Comment by TheQwertiest** [comment]
Could you supply the required images and corresponding drawing code, please?

**Comment by elia-is-me** [comment]
> 
> 
> Could you supply the required images and corresponding drawing code, please?

... sorry, something was wrong in my code... i should check more carefully

**Comment by TheQwertiest** [comment]
:D
