### ISSUE TITLE
utils.InputBox automatic height adjustment

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#71]
Hello,

Probably a not-too-hard to fix little issue:
It look like utils.InputBox doesn't extend the dialog height according to the text.

For ex:
utils.InputBox(window.ID, "Ligne 1\nLigne 2\nLigne 3\nLigne 4\nLigne 5\nLigne 6\nLigne 7\nLigne 8\nLigne 9\nLigne 10\nLigne 11\nLigne 12\nLigne 13\n", "test", "");

Thanks for reading : )

**Comment by TheQwertiest** [comment]
This is actually a rather non-trivial issue, but it would be nice to have it fixed.

**Comment by Ottodix** [comment]
Ok, thanks. I've got some other errors related to the dialog boxes, actually when i draw them using activeXscript, it trigger the slow script detection after some time. I'll open a new script ticket
