### ISSUE TITLE
slow script detection when drawing dialog boxes using activeXscript

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#72]
Hi,

The slow script detection mecanism trigger on activeXscript objects. When a dialog box is built using this method, it stop the script execution until the dialog is closed, so of course the slow script detection active itself after some time.

Here is a code which show this behavior. This code draw a counter which is incremented while playing a track. After 3 seconds, it open a dialog box built using an ActiveXObject. You'll that the counter stop increasing itself until the dialog is closed:
```
var vb = {};
vb.Function = function (func) {
    return function () {
        return vb.Function.eval.call(this, func, arguments);
    };
};

vb.Function.eval = function (func) {
    var args = Array.prototype.slice.call(arguments[1]);
    for (var i = 0;
    i < args.length;
    i++) {
        if (typeof args[i] != 'string') {
            continue;
        };
        args[i] = args[i].replace(/"/g, '" + Chr(34) + "') ;
		args[i] = '"' + args[i].replace(/\n/g, '" + Chr(13) + "') + '"';		
    };
    var vbe = new ActiveXObject('ScriptControl');
    vbe.Language = 'VBScript';
    return vbe.Eval(func + '(' + args.join(', ') + ')');
};

var execution_counter = 0;
function on_paint(gr){
	gr.GdiDrawText(execution_counter, gdi.Font("Segoe UI", 12, 0), 0xff000000, 10, 10, 100, 100);
	execution_counter++;
	if(execution_counter==3){
		var MsgBox = vb.Function('MsgBox');
		var result = MsgBox("test slow script detection ?", 4, "Please confirm");		
	}
}
function on_playback_time(){
	window.Repaint();
}
```

I know that there is utils.ShowHtmlDialog, and it's possible to do exactly the same thing with an html form, but unfortunately this function crashs randomly on my foobar. I can open a new ticket if you want for that, because actually this one wouldn't be a problem if the utils.ShowHtmlDialog didn't crash, let me know!

**Comment by TheQwertiest** [comment]
> I can open a new ticket if you want for that, because actually this one wouldn't be a problem if the utils.ShowHtmlDialog didn't crash, let me know

That would be preferable, since I'm not sure if I can do anything with ActiveX dialog creation :\

**Comment by Ottodix** [comment]
Ok, i did. Then i guess this ticket could be closed, i let you choose.

**Comment by TheQwertiest** [comment]
I'll close it if I'm unable to find the solution (since there actually might be one).
