### ISSUE TITLE
foobar crash when using utils.ShowHtmlDialog

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#73]
Hi,

So, this issue trigger randomly, on my config most of the time after something like 10 dialogs opened and closed. It happened even with the sample from marc2k3(?) in foobar2000\components\foo_spider_monkey_panel\samples\basic\HtmlDialogWithCheckBox.js., even when this sample is the only panel of a PSS config (but then it takes more trials before crash)

I uploaded the .dmp and .txt error report created by foobar (failure_00000024 files), and a dmp created just after the crash using the windows task manager (foobar2000_htmlDialogCrash.DMP)
https://drive.google.com/drive/folders/1rOSPUMpl1sc9JvKGrybsJLFEwGpAJr_s?usp=sharing

thanks!

**Comment by TheQwertiest** [comment]
Thanks for the bug report, I'll look into it!

>  even with the sample from marc2k3(?)

Not, that it matters much, but this sample is mine =)

**Comment by TheQwertiest** [comment]
Should be fixed in the latest build (once it's ready).

**Comment by Ottodix** [comment]
Great! Thanks a lot
