### ISSUE TITLE
Dialog from utils.ShowHtmlDialog does not handle hot keys properly

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#74]
Hi!
Sorry for this serial of issues with utils.ShowHtmlDialog , but i just discovered another one.

On an active utils.ShowHtmlDialog box, hitting the entry key doesn't trigger the html element where the focus is, like it should. Instead, it close the html dialog like hitting the escape key.
You can reproduce this with the basic sample provided by the component, called HtmlDialogWithCheckBox.js

Have a good evening, if this is the evening in your country

**Comment by TheQwertiest** [comment]
Note, you have to handle `Enter` button manually in html now - the sample will be updated accordingly soon.

**Comment by Ottodix** [comment]
Cool, thanks! I managed to update my htmlDialogs buttons 

if another guy come there and need to do the same, it's quite easy to do just add onkeydown="if(event.keyCode == 13) this.click()" to the html <button> balise, like that
`<button onkeydown="if(event.keyCode == 13) this.click()">Yes</button>`

**Comment by TheQwertiest** [comment]
FYI: https://github.com/TheQwertiest/foo_spider_monkey_panel/commit/7e71f150f274ef517ecf53a50d6405c1ed45d853

**Comment by Ottodix** [comment]
Yep, your code is a more elegant and generic solution.
