### ISSUE TITLE
Copy via DoDragDrop blocks the main thread until the operation is finished

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#75]
HI!

When you do a drap and drop from a smp panel and out of foobar window, all smp panels are frozen during the whole copy operation. So if you copy a lot of tracks from a smp panel to an usb key for example, you won't be able to use foobar during 10 min.

I found that sentence in the doc, which seems to indicate that it's normal behavior: "DoDragDrop blocks code execution until the drag operation is finished (callbacks will be called properly though)"
I'm asking just in case it's not supposed to apply to the whole copy duration.

If a code sample could help, i can provide you that.

tchô

**Comment by TheQwertiest** [comment]
Can't be fixed by me - it requires changes in fb2k API (see https://hydrogenaud.io/index.php/topic,117724.new.html for more info).

I will leave the issue open until there is an answer from Peter.

**Comment by Ottodix** [comment]
Ok, thanks! It seems very probable that peter will look at this issue, if it occurs also with the default playlist viewers

**Comment by TheQwertiest** [comment]
Fixed in foobar2000 v1.5

**Comment by Ottodix** [comment]
Cool, it's a lot more convenient now when i copy tracks to a usb key (which is something i do quite often, for listening my latest found music gems in my car : )
Thanks for reporting to peter or for whatever you did.
