### ISSUE TITLE
window properties

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#76]
@TheQwertiest , reading your forum thread today, you seem to be unaware of the `window` `MinWidth`, `MaxWidth`, `MinHeight` and `MaxHeight` properties. These were in WSH panel mod way before UI hacks was a thing.

Pinging @cerbaire as well...

For the purpose of the following examples, UI hacks and locking splitters are not used at all

These can be used lock internal dimensions of each panel. It is fully respected in default UI where you can have a single panel layout and add code like this...

```js
window.MinHeight = window.MaxHeight = window.MinWidth = window.MaxWidth = 400;
```

This will prevent you from resizing the main foobar window and if you maximise, it will snap to the top left as expected.

You can of course set them independently to restrict min/max sizes without locking.

In Columns UI, the behaviour isn't as clearly defined. You cannot use it with any one panel taking up the entire width or height of the layout because the overall window size cannot be locked from within and if you had a single panel layout with the above code, it would appear not to work at all.

But it is respected if you had a layout like this...

![Untitled](https://user-images.githubusercontent.com/34617027/59622223-e3518280-9128-11e9-800b-7919a5155f0a.png)

You can add the same code example and it will be respected/locked because it doesn't involve trying to lock the main window size in any way. The splitters will refuse to move even though they are not locked. 

In this example where you have a single panel taking up the entire width of layout, you can't restrict the width but you can lock the height...

```js
window.MinHeight = window.MaxHeight = 200;
```

![Untitled](https://user-images.githubusercontent.com/34617027/59622577-dc773f80-9129-11e9-9f9d-05a1cc2a5299.png)

Hope that clears things up!

**Comment by TheQwertiest** [comment]
@marc2k3 , I was/am aware that these properties were in WSH panel, but they are not available in JSP nor SMP. The distinction had to be pointed out, so that users won't expect for the bugs in `foo_ui_hacks` API to be fixed by SMP.

**Comment by marc2k3** [comment]
You clearly haven't read a single word I wrote.

**Comment by TheQwertiest** [comment]
Oh crap... I *did* misread both him and you! It was me who confused JSP/JSP `MinWidth` with `MinSize` from `foo_ui_hacks`...

PS: And I have read your wall of text =(
