### ISSUE TITLE
Some keyboard keys not working in utils.ShowHtmlDialog

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#79]
Hi,
A guy just send me a message about this: On the input box of a html dialog, the following keys (and mouse) hits aren't recognized: 

- space
- delete (not so important imho)
- right click (same...)

You can use the HtmlDialogWithCheckBox.js sample in order to reproduce this, you can then replace in PopupWithCheckbox.html the "Placeholder main text" by 
`<input id="input" name="inputs" value="input_default_values"></input>`

Have a good day!

**Comment by TheQwertiest** [comment]
Should be fixed in the latest build (once it's done building).
Note: now you don't have to handle `space` and `enter` key presses manually.

**Comment by Ottodix** [comment]
Yep, I just tried the nighly build, and it works perfectly now. Thanks a lot!
