### ISSUE TITLE
Add promises/await/async support

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#8]
Any attempted usage of these causes an instant crash. I tried the example on this page...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

Obviously I used `window.SetTimeout`.

Incidentally, I have a separate repo setup containing my samples all updated to use let/const/arrow functions etc. I'll try and modernise more as I learn.

https://github.com/marc2k3/smp_2003

I will provide working versions of those JS Smooth scripts at some point but they won't be getting the same treatment. I'm having issues with their image caching behaviour going all weird - no script errors so it's very hard to debug - it's just the end results are all wrong.

**Comment by TheQwertiest** [comment]
I will test it out, thanks!

> I have a separate repo setup containing my samples

Haha, actually I wanted to suggest that (i.e. to make a separate repo for your scripts, where you could commit without the need of PRs) =)

> I'm having issues with their image caching behaviour going all weird

I'm not sure if it is related, but currently JS errors that occur in ActiveX context might be silently supressed, e.g.: 
```
xmlhttp.onreadystatechange = function () {
    undefined_func.fail(); ///< throws JS error inside
} ///< does not throw JS error
```
I'm still looking for ways, to workaround that.

**Comment by marc2k3** [comment]
> I'm not sure if it is related, but currently JS errors that occur in ActiveX context might be silently supressed, 

That's good to know - I thought I was going mad fixing up my own scripts. I was using `WshShell.popup` inside `onreadstatechange` which was silently failing and I had no idea why. Of course when I tried it standalone, I realised the `Popup` should begin with capital P.

**Comment by TheQwertiest** [comment]
Sorry for that =) Will be added to the docs somewhere

**Comment by TheQwertiest** [comment]
It seems that `async` and friend are not supported by default, I have to implement some things manually.

**Comment by marc2k3** [comment]
No problemo. You can't miss what you've never had.

**Comment by TheQwertiest** [comment]
Note: my current async implementation is a bit lacking - async tasks will only be invoked when some callback is invoked (e.g. on_paint), so no callback invocations equals to no async invocations.

**Comment by marc2k3** [comment]
OK, thanks for that. :+1:

**Comment by TheQwertiest** [comment]
Re-implemented async handling (corresponding commit: https://github.com/TheQwertiest/foo_spider_monkey_panel/commit/ed5434274f6752bf00d830968ca4152204760ddf) - now it should work properly.

**Comment by marc2k3** [comment]
Nice.
