### ISSUE TITLE
PFC license

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#80]
Since you're using the preview SDK, the PFC license has been changed from `unlicense` to `zlib`. You'll need to update the file distributed with the component and your third party notices file.

Not doing a PR because the JSON submodule is so ridiculously large and my internet is slow!

**Comment by TheQwertiest** [comment]
Thanks for the notice!

> because the JSON submodule is so ridiculously large and my internet is slow!

Submodules are not downloaded by default though? =)
But it *is* huge... Or more like it's commit history size is huge - it's the first (and the only) submodule which required the use of shallow copy...
