### ISSUE TITLE
No error popup on player startup (e.g. broken script)

### ISSUE THREAD

**Issue by TheQwertiest** [TheQwertiest/foo_spider_monkey_panel#82]

**Comment by marc2k3** [comment]
You can massively simplify this by using `fb2k::inMainThread` from the SDK...

https://github.com/TheQwertiest/foobar2000-sdk/blob/5da544d5a2d73c96437af9a11fdcedc9fa4081e2/SDK/main_thread_callback.h#L4-L14

Example usage:

https://github.com/marc2k3/foo_jscript_panel/blob/7620b96f019c68b16944d09a68005be573ac98f1/src/script_host.cpp#L368-L370

**Comment by TheQwertiest** [comment]
> doesn't work if you spawn a popup during DllMain>DLL_PROCESS_ATTACH which my component never does

Neither does mine =)
`DLL_PROCESS_ATTACH` has very strict (and obscure) limits on what can be invoked there, so only necessary (and strictly verified) things should be put in there.

> You can massively simplify this by using fb2k::inMainThread

I do trust you that it works and solves this issue, but I can't find anything in the docs that mentions this particular issue I'm trying to solve: all the popup calls are invoked in the main thread already, it's just the timing of these calls that're problematic. Did you get some additional description from Peter?

**Comment by marc2k3** [comment]
I didn't confirm anything with Peter. 

Not sure where the idea came from but I originally refactored the ancient popup_msg/delay_loader code from WSH panel mod to use `main_thread_callback` from the SDK in this commit:

https://github.com/marc2k3/foo_jscript_panel/commit/3a03f8e096850ea7de18a6df60435c0fc42c1dc9

It was a few months later when I discovered the `inMainThread` lambda thingy which allowed me to simplify it some more.

https://github.com/marc2k3/foo_jscript_panel/commit/ab87f59602512ed022f9715f473c616c91b3d658

**Comment by TheQwertiest** [comment]
@marc2k3 , I've got the confirmation about `inMainThread` =)
https://hydrogenaud.io/index.php?topic=117208.msg977811#msg977811

**Comment by marc2k3** [comment]
I suppose if you defer script initialisation the same way, you could remove popup message hacks altogether.

**Comment by TheQwertiest** [comment]
Hm... That might actually work. Need to investigate...

**Comment by marc2k3** [comment]
I've gone for it. https://github.com/marc2k3/foo_jscript_panel/commit/456bc3076a1ba0b27b963a556e828d270bc852ad
