### ISSUE TITLE
Some Spider Monkey Panel compatibility

### ISSUE THREAD

**Issue by 2ji3150** [TheQwertiest/foo_spider_monkey_panel#84]
- ActivXObject often does not function properly.

The basic WScript.Shell Environment property doesn't work, or WMPlayer.OCX throws an error that the Controls property doesn't exist. Things like that happen.
Strictly, Read () of ADODB.Stream stops with an error.

- BinaryString cannot be generated.

String.fromCharCode (0,82);
In WSH Panel and JScript Panel, CharCode (0) can be properly acquired as a character, and for example, WriteText () of ADODB.Stream can output it as expected. However, this is not possible with SMP, and it is virtually impossible to handle BinaryString.
Generating an arbitrary ArrayBuffer with Uint8Array, etc. seems to be impossible to handle with ADODB.Stream and XMLHTTP.

**Comment by TheQwertiest** [comment]
This might have been already fixed on the matter branch. Could you provide some code that reproduces those issues, so that I can verify the fix?
PS: Regretfully, I currently can't provide you a SMP build for testing, because of Microsoft shenanigans.

**Comment by 2ji3150** [comment]
Sorry, this is forwarded  and translated from the someone's developing blog on June 21.
If the bug is still existed I'll let you know.
