### ISSUE TITLE
fb.StopAfterCurrent is not a function

### ISSUE THREAD

**Issue by CultofRobots** [TheQwertiest/foo_spider_monkey_panel#88]
fb.StopAfterCurrent is listed as a method in SMP editor but the following error occurs when used in `playback buttons.js`:

```
Error: Spider Monkey Panel v1.2.2-preview+0db3c6a4 (Playback Buttons by marc2003)
fb.StopAfterCurrent is not a function

File: <main>
Line: 13, Column: 145

Stack trace:
  buttons.update/buttons.buttons.stopaftercurrent<@<main>:13:145
  _button/this.lbtn_up@helpers.js:26:4
  _buttons/this.lbtn_up@helpers.js:88:4
  on_mouse_lbtn_up@<main>:26:2

```

Code used in `playback buttons.js` replacing lines 13 with the following line:
`buttons.buttons.stopaftercurrent = new _button(0, 0, bs, bs, {normal : 'buttons\\stop.png'}, (x, y) => { fb.StopAfterCurrent(); }, 'Stop After Current');`

**Comment by Wil-B** [comment]
From the documenation it seems as though it should be fb.StopAfterCurrent not fb.StopAfterCurrent()

Try:

```
buttons.buttons.stopaftercurrent = new _button(0, 0, bs, bs, {normal : 'buttons\\stop.png'}, (x, y) => { fb.StopAfterCurrent = !fb.StopAfterCurrent; }, 'Stop After Current');
```

**Comment by CultofRobots** [comment]
That works. Thanks.

**Comment by marc2k3** [comment]
For this to be really useful, ideally you'd want to display different images depending on the current state of `fb.StopAfterCurrent` and update the display from the `on_playlist_stop_after_current_changed` callback so any changes from the track stopping/getting the setting changed via other means such as the menu/keyboard shortcuts are reflected visually.
