### ISSUE TITLE
EstimateLineWrap

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#9]
There *might* be a problem with this but it's quite difficult to reproduce. There is no script error or crash but it just hangs indefinitely eating up 25% of cpu (quad core i5). Using `Process Explorer`, this is what raised my suspicions...

![untitled](https://user-images.githubusercontent.com/34617027/45986845-e1f59c80-c065-11e8-95b9-0f3bb43ba2f3.png)

Curiously, the GDI handle count is 10000 which is a nice round number!!

![untitled](https://user-images.githubusercontent.com/34617027/45986865-09e50000-c066-11e8-8830-c926d5b099f6.png)

**Comment by TheQwertiest** [comment]
Do you have a specific piece of code that triggers this slowdown/GDI handle leak?

**Comment by marc2k3** [comment]
It originally happened twice without doing anything abnormal - I have just 2 scripts which make use of it - last.fm bio and allmusic review. Both of these use the function to split chunks of text in to arrays which is the only way scrolling is possible. Under normal usage, it would only get called on artist/album change or panel resize.

Since it happened, it's proven really hard to reproduce and it needs serious abuse inside a timer to trigger it again. Even then, it can take a couple of minutes to happen...

```js
include(fb.ComponentPath + "samples\\complete\\js\\lodash.min.js");
include(fb.ComponentPath + "samples\\complete\\js\\helpers.js");

var text = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Fusce aliquam vestibulum ipsum. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nullam eget nisl. Maecenas lorem. Aliquam ornare wisi eu metus. Etiam bibendum elit eget erat. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.';
var font = gdi.Font('Segoe UI', 12);

window.SetInterval(function () {
    var width = Math.floor(Math.random() * 1000) + 100; // i never call the function when the panel is less 100 pixels wide
    var tmp = _.lineWrap(text, font, width);
    console.log(tmp.length);
}, 50);
```

**Comment by marc2k3** [comment]
My lineWrap function is a lodash mixin inside helpers.js...

```js
    lineWrap:             function (value, font, width) {
        var temp_bmp = gdi.CreateImage(1, 1);
        var temp_gr = temp_bmp.GetGraphics();
        var result = [];
        _.forEach(value.split('\n'), function (paragraph) {
            var lines = _.filter(temp_gr.EstimateLineWrap(paragraph, font, width), function (item, i) {
                return i % 2 === 0;
            });
            result.push.apply(result, _.map(lines, _.trim));
        });
        temp_bmp.ReleaseGraphics(temp_gr);
        temp_gr = null;
        temp_bmp = null;
        return result;
    },
```

I tested the code with just the creating/nulling of a temp image and that's fine - it has nothing to do with the repeated use of gdi.CreateImage/GetGraphics/ReleaseGraphics.

**Comment by TheQwertiest** [comment]
> it has nothing to do with the repeated use of gdi.CreateImage/GetGraphics/ReleaseGraphics.

Actually it has, it seems that for some reason created images are leaking (you can check it visually through task manager > details > enable GDI objects column). Now I only to understand why it's happening...

**Comment by TheQwertiest** [comment]
Okay, I see the problem now: these objects are really small, so they don't trigger GC, and this makes them remain in the memory for far too long. I need to rethink my GC triggers\strategy...

**Comment by TheQwertiest** [comment]
PS: 10k is default Windows limit for Gdi handles.

**Comment by marc2k3** [comment]
Thanks. 

Before you fixed this, I was wondering if creating a temp image on startup and not killing it might help?? Currently, I have these 2 functions... 

```js
function _lineWrap (value, font, width) {
	let temp_bmp = gdi.CreateImage(1, 1);
	let temp_gr = temp_bmp.GetGraphics();
	let result = [];
	_.forEach(value.split('\n'), (paragraph) => {
		let lines = _.filter(temp_gr.EstimateLineWrap(paragraph, font, width), (item, i) => i % 2 == 0);
		result = [...result, ...(_.map(lines, _.trim))];
	});
	temp_bmp.ReleaseGraphics(temp_gr);
	temp_gr = null;
	temp_bmp = null;
	return result;
}

function _textWidth (value, font) {
	let temp_bmp = gdi.CreateImage(1, 1);
	let temp_gr = temp_bmp.GetGraphics();
	const width = temp_gr.CalcTextWidth(value, font);
	temp_bmp.ReleaseGraphics(temp_gr);
	temp_gr = null;
	temp_bmp = null;
	return width;
}
```

I was thinking of refactoring like this this..

```js
let temp_bmp = gdi.CreateImage(1, 1);
let temp_gr = temp_bmp.GetGraphics();

function _lineWrap (value, font, width) {
	let result = [];
	_.forEach(value.split('\n'), (paragraph) => {
		let lines = _.filter(temp_gr.EstimateLineWrap(paragraph, font, width), (item, i) => i % 2 == 0);
		result = [...result, ...(_.map(lines, _.trim))];
	});
	return result;
}

function _textWidth (value, font) {
	return temp_gr.CalcTextWidth(value, font);
}
```

**Comment by TheQwertiest** [comment]
It's hard to tell without profiling, for example, image creation might be much faster than CalcTextWidth, thus producing only a subtle performance gain.
In my experience (during CaTRoX development) performance bottlenecks are usually not in the place you expect them to be :D
