### ISSUE TITLE
Crash when dragging a track without/missing cover art

### ISSUE THREAD

**Issue by VNRARA** [TheQwertiest/foo_spider_monkey_panel#96]
Error: Spider Monkey Panel v1.2.2-preview+0db3c6a4 (GraphicBrowser v1.2.0 by Ottodix)
img is undefined

File: JStheme_common.js
Line: 2574, Column: 2

Stack trace:
  createDragImg@JStheme_common.js:2574:2
  on_mouse_move@WSHgraphicbrowser.js:6223:20

**Comment by TheQwertiest** [comment]
This script is not a part of SMP, so I can't help you much.
You should report this issue in the corresponding repository: https://github.com/Ottodix/Eole-foobar-theme.
